### ISSUE TITLE
Noto Mono vs Noto Sans Mono

### ISSUE THREAD

**Issue by sommerluk** [googlei18n/noto-fonts#1000]
I wonder what is the relationship of Noto Mono (only one style) and Noto Sans Mono (various weights/width)…

**Comment by dougfelt** [comment]
​Noto Sans Mono is the updated version built from sources. We don't have a
hinted version of this font. Noto Mono is the old version and there is a
hinted version of it.  I expect we should remove Noto Mono.

**Comment by ytx21cn** [comment]
You can see the difference in the letter g.

**Comment by dougfelt** [comment]
Noto Sans Mono is a replacement and not just an update. The entire build
process is different. Some glyphs will change. We do not have a
comprehensive description of the differences.

**Comment by marekjez86** [comment]
Thank you for pointing this out. We will remove Noto Mono.

**Comment by sommerluk** [comment]
Seems to be resolved by #1029

**Comment by marekjez86** [comment]
To resolve some of the confusion about some glyphs with serifs I renamed NotoSansMono font back to NotoMono (although we have already Sans fonts that look more "Serif-like" which we will keep as Sans; e.g., NotoSansBhaiksuki , NotoSansCherokee , ...).

**Comment by wyuenho** [comment]
Ah, this explains why Noto Sans Mono is missing after wiping all Noto fonts from my system and reinstalling with master.

I'm not sure what to make of this decision TBH. It feels like it doesn't matter since Sans Mono has been out for so long and people already know it's a replacement for the old Mono. Would be nice if you could somehow alias the two in a OTC/TTC or something.

**Comment by moyogo** [comment]
@wyuenho See https://github.com/googlefonts/noto-fonts/issues/1126#issuecomment-665792754, the name may not change after all.

**Comment by wyuenho** [comment]
@marekjez86 Are you planning to change the name back?
