### ISSUE TITLE
Noto Sans Chakma font not covered all Chakma special words yet

### ISSUE THREAD

**Issue by Bivuti** [googlei18n/noto-fonts#1134]
Hi,
I found that your "Noto Sans Chakma.ttf" font doesn't correct rendering some special Chakma words yet. I attached the rendering compare screenshot for your kind attention. 
![kkai](https://user-images.githubusercontent.com/13092086/38458630-43a71866-3ac2-11e8-9ab8-96536bdd9c31.PNG)
![kkai-noto](https://user-images.githubusercontent.com/13092086/38458646-4e1545d4-3ac2-11e8-8a4d-d6860ab0cf50.PNG)

Please take a look at this issue. 

Thanks
Bivuti Chakma

**Comment by marekjez86** [comment]
@Bivuti : why is this one incorrect?

![chakma-incorrect](https://user-images.githubusercontent.com/13322623/38458889-f99d46c4-3a57-11e8-8e08-5b22a8c867ff.jpeg)

why is this one correct?

![chakma-correct](https://user-images.githubusercontent.com/13322623/38458904-042bc61a-3a58-11e8-9223-8b7b37d02daa.jpeg)

are both of them readable by the native users?

**Comment by punchcutter** [comment]
![chakma_maayyaa](https://user-images.githubusercontent.com/11257204/38459058-d552ad3e-3a59-11e8-92ba-863f41c00c55.png)
This works in Noto Chakma when the order of marks is the other way around (1112D 11134), but that order doesn't even make any sense because that would mean it's considered a Pure Killer (the original Indic Syllabic Property) so no vowel would follow it. The Indic Syllabic Property was then changed to Gemination Mark. That means the lookup that does work in Noto Chakma is backwards. According to the original properties that would have been correct, but since 11134 has changed this lookup needs to be updated. I'll fix it.

**Comment by Bivuti** [comment]
@punchcutter The first question answer is Noto Sans Chakma not rendering well of this sequences U+11107 U+11134 U+1112D =  𑄇𑄴𑄭. So it's incorrect as the people could not spell out it In Chakma.

The second question is RibengUni well rendering of this sequences U+11107 U+11134 U+1112D =  𑄇𑄴𑄭. So it's correct. People easy spell out this word.

Here is also some special Chakma words that still not well rendering your Noto Sans Chakma font. The comparison text is given as below: 
![01](https://user-images.githubusercontent.com/13092086/38466881-918a3bf0-3b51-11e8-88ca-4df33cd35a68.png)
![02](https://user-images.githubusercontent.com/13092086/38466882-91cbe3ca-3b51-11e8-968c-7a9b0bbde17f.png)

Please also update this one.

Thanks
Bivuti

**Comment by punchcutter** [comment]
Ok Bivuti, no problem. When you put a screenshot can you please also put the raw text or codepoints? That helps so that anyone can test the issue. 
For this issue we now have
U+11107 U+11134 U+1112D = 𑄇𑄴𑄭
U+11107 U+11134 U+11130 = 𑄇𑄴𑄰
Those will be fixed in the next update.

**Comment by Bivuti** [comment]
@punchcutter  Thanks for your suggestion. Sounds great! I would be happy that to help you about Chakma Language any confusion/complicated words when you will be implementing in modern technology. And also any Chakma font issue.

Cheers
Bivuti
