### ISSUE TITLE
question: does Noto Naskh Arabic UI need special-handling of Allah and Muhamed? 

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#1371]
This is a "dual" of #836.   

Noto Sans Arabic adds 'missing' Tashkils to Allah (Alef, Lam, Lam, Heh) and Muhamed. So does Arial. 

See https://docs.google.com/document/d/1EtUb0MIOPgO2nJn_9Uvu_iEl4fUztVqMKH-UAVBf6J4/edit . 
7 out of 19 fonts do that while 12 fonts don't in the document. 

Is it BETTER for  Noto Naskh Arabic (UI) to do the same than not ?  

@roozbehp @behdad @nizarsq @kmansourMT @marekjez86

**Comment by jungshik** [comment]
@khaledhosny

**Comment by khaledhosny** [comment]
It is acceptable for a UI font to not handle Allah-form, there are many Arabic and non-Arabic words that end with the same sequence of letters and do not mean name of God. I don’t even think Noto Sans should add the marks either, Noto Naskh intentionally didn’t and that is a good default behavior. Muhammed definitely shouldn’t use a special form, it is a common Arabic name and the special calligraphic form is only used when referring to the prophet, otherwise it looks very odd. Arial is definitely wrong here, it is some oddity  some Microsoft acquired of late.

**Comment by jungshik** [comment]
Thanks a lot, @khaledhosny , for your prompt reply. I agree with you in principle. 

It became a bit tricky. Apparently some people got used to Arial's behavior and complained about this Google search result in Arabic, Urdu or Farsi (that uses Noto Naskh Arabic UI as a web font). 

https://www.google.com/search?q=%D8%A7%D9%84%D9%84%D9%87&hl=ar

**Comment by khaledhosny** [comment]
I think the rendering in the page above is very reasonable and acceptable, it uses a shorter second lam as expected in the Allah form, but does not add the shadda and small alef, so it is a good compromise and would still work when the sequence lam lam heh is not an Allah.

**Comment by behdad** [comment]
I fully agree with khaled.

**Comment by kmansourMT** [comment]
Thank you, Khaled and Behdad, for the affirmation.

**Comment by nizarsq** [comment]
As @khaledhosny said I believe the name Mohammed shouldn’t use a special form since it’s not possible to know if the the name mohamad is referring to the prophet or to a person name. For Allah (Alef, Lam, Lam, Heh), It is ok not to use special form in Noto Naskh Arabic UI, user still have the option to add them manually if needed.

**Comment by jungshik** [comment]
Thank you all. I'm closing this as WAI.
