### ISSUE TITLE
Can not display noto sans kr in Italic

### ISSUE THREAD

**Issue by hechangjiu** [googlei18n/noto-fonts#1466]
### Font 
Noto Sans KR

### Font Version
Android

**Comment by marekjez86** [comment]
We do not have any plans for Italic versions of Noto CJK script. If you want to use Latin, Greek and Cyrillic subset of CJK using Italic please use NotoSans-Italic font.

**Comment by marekjez86** [comment]
@hechangjiu : what was that you were doing. Could you describe it?

**Comment by kenlunde** [comment]
@hechangjiu: @marekjez86 is absolutely correct that _Noto Sans KR_ does not include any italic glyphs, which is both intentional and by design, and that there are no plans to do so. In case you were not aware, CJK fonts without italic glyphs are the norm, not the exception.

In addition, the Western glyphs in _Noto Sans KR_ (and other _Noto CJK_ fonts for that matter) are derived from [_Source Sans Pro_](https://github.com/adobe-fonts/source-sans-pro/), so you're actually better off using _Noto Sans_ as suggested, or _Roboto_, when composing

**Comment by hechangjiu** [comment]
Well, Thank you for your comments. Now I know that noto sans cjk is not include italic by design. This issue should be closed as by design.
