### ISSUE TITLE
Santali Fonts for Enhancement

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#155]
```
What steps will reproduce the problem?
1. How to add font in Santali Language?
2. Could it view as original?
3. How to issue in chrome book?

What is the expected output? What do you see instead?
I want to use in chrome book for preparing Santali Books.

What version of the product are you using? On what operating system?
Chromebook laptop. Chrome OS.


Please provide any additional information below.
It is not included in the so far.

```

Original issue reported on code.google.com by `kmurmu918@gmail.com` on 22 Sep 2014 at 5:31

Attachments:
* [ol_chiki_classic.ttf](https://storage.googleapis.com/google-code-attachments/noto/issue-155/comment-0/ol_chiki_classic.ttf)
* [ol_chiki_old.ttf](https://storage.googleapis.com/google-code-attachments/noto/issue-155/comment-0/ol_chiki_old.ttf)
* [ol_chiki_optimum.ttf](https://storage.googleapis.com/google-code-attachments/noto/issue-155/comment-0/ol_chiki_optimum.ttf)
* [Ol_Chiki_Regular.ttf](https://storage.googleapis.com/google-code-attachments/noto/issue-155/comment-0/Ol_Chiki_Regular.ttf)
* [ol_chiki_royal.ttf](https://storage.googleapis.com/google-code-attachments/noto/issue-155/comment-0/ol_chiki_royal.ttf)
* [olchiki_usara.ttf](https://storage.googleapis.com/google-code-attachments/noto/issue-155/comment-0/olchiki_usara.ttf)
* [sant_b02.ttf](https://storage.googleapis.com/google-code-attachments/noto/issue-155/comment-0/sant_b02.ttf)
* [santalifont.ttf](https://storage.googleapis.com/google-code-attachments/noto/issue-155/comment-0/santalifont.ttf)
* [wesantals.ttf](https://storage.googleapis.com/google-code-attachments/noto/issue-155/comment-0/wesantals.ttf)

**Comment by brawer** [comment]
[cross-posting from https://github.com/googlei18n/noto-fonts/issues/160]

So I just grabbed a couple ChromeBooks and checked how Santali (in the “Ol Chiki” script) looks on ChromeOS. One test machine had the “stable” channel (version 41.0.2272.89, platform 6680.64.0), and two had the “beta” channel (version 44.0.2403.54, platform 7077.49.0) of ChromeOS. On all three ChromeBooks, the Ol Chiki glyphs were getting displayed correctly. ChromeOS used the “Noto Sans Ol Chiki” font that ships with ChromeOS.
https://en.wikipedia.org/wiki/Ol_Chiki_alphabet#Unicode_chart
https://en.wikipedia.org/wiki/Ol_Chiki_(Unicode_block)
http://www.google.com/get/noto/#sans-olck

So, there does not seem to be any rendering or font problem — if a web page contains Santali (Ol Chiki) text, today’s version of ChromeOS will display it perfectly fine. However, to be useful for people, users would also need some way for entering text in Santali. Here's a document that describes how text input works on ChromeOS:
https://www.chromium.org/chromium-os/chromiumos-design-docs/text-input#TOC-Basic-architecture
(ChromiumOS is the open-source foundation of ChromeOS)

According to that overview document, text input on ChromeOS is based on iBus:
https://github.com/ibus/ibus/wiki

Therefore, at least if I understand this correctly (others on this bug: please correct me if I'm wrong), the next step would be to implement a Santali input method in iBus. Because iBus is an open-source project, anyone can do this — you don't need to wait for Google. This work would be useful ChromeOS, but also for any other systems that use iBus.

**Comment by brawer** [comment]
Update: I've checked with the ChromeOS team, and they told me that they moved away from iBus. Instead, there is now a very simple JavaScript API:
https://developer.chrome.com/extensions/input_ime
http://src.chromium.org/viewvc/chrome/trunk/src/chrome/common/extensions/docs/examples/api/input.ime/basic/

*However*, looking at the picture that was posted earlier on this bug, a simple keyboard might be enough for Ol Chiki:

![keyboard-olck](https://cloud.githubusercontent.com/assets/1527880/8429270/53b2963c-1f26-11e5-8461-df8e2159b376.jpg)

For simple keyboards mappings, ChromeOS uses XKeyboardConfig. Can you write a configuration file, (this should be quite easy), and test it on a Linux machine? I believe that X11 does not yet have an Ol Chiki keyboard, so your work would be useful beyond ChromeOS.
http://www.freedesktop.org/wiki/Software/XKeyboardConfig/

**Comment by xiangyexiao** [comment]
Close this issue since it is not font related.
