### ISSUE TITLE
Noto Sans Balinese renders second-level conjunct consonants smashed into first-level conjuncts

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#373]
```
What steps will reproduce the problem?
1. Use a current version of Firefox or Chrome.
2. Go to http://lindenbergsoftware.com/google/noto/bali-double-conjunct.html
3. Check the rendering of second-level conjunct consonants with Noto Sans 
Balinese, and compare it with a reference rendering and the rendering in Aksara 
Bali. 

What is the expected output? What do you see instead?
The consonants ya, wa, ra can occur as second-level conjuncts, and should then 
be rendered below the first-level conjunct consonants, which in turn are 
rendered below base consonants. Instead, Noto Sans Balinese renders them 
smashed together at the same height.

What version of the product are you using? On what operating system?
Noto Sans Balinese 1.02
Firefox 38.0 and Chrome 42.0.2311.152
OS X 10.10.3
```

Original issue reported on code.google.com by `googled...@lindenbergsoftware.com` on 15 May 2015 at 10:32

Attachments:
- [bali-double-conjunct.png](https://storage.googleapis.com/google-code-attachments/noto/issue-373/comment-0/bali-double-conjunct.png)

**Comment by NorbertLindenberg** [comment]
Please label this bug as Script-Balinese.

**Comment by NorbertLindenberg** [comment]
@kmansourMT requested the plain text version of the sample words used in the test case:
ᬒᬁᬲ᭄ᬯᬲ᭄ᬢ᭄ᬬᬲ᭄ᬢᬸ
ᬲ᭄ᬢ᭄ᬭᬷ
ᬩ᭄ᬭ᭄ᬬᬕ᭄
ᬯᬺᬱᬵᬲ᭄ᬢ᭄ᬭ
ᬩᬗ᭄ᬓ᭄ᬯᬂ
ᬘᬦ᭄ᬤ᭄ᬭ

Here's a screen shot of the rendering of these words in the current version 1.10 of the Ubud font, the enhanced version of Noto Sans Balinese that's included in the [Balinese Font and Keyboard](http://lindenbergsoftware.com/balinese) app:
![ubud rendering](https://cloud.githubusercontent.com/assets/216206/12898473/b46e9e22-ce61-11e5-8664-3a1401f64eb9.png)

**Comment by kmansourMT** [comment]
In the upcoming version of Noto Balinese, second-level conjuncts will display correctly as demonstrated in the following graphic:

![373-text-after_correction](https://cloud.githubusercontent.com/assets/12738181/13412436/21b10fdc-def8-11e5-9aa4-ddf2123e4312.png)

**Comment by NorbertLindenberg** [comment]
The rendering in the previous comment looks like the bug has been fixed, but a year later I still can’t find an updated version of the font that actually produces that rendering.

The version at [unhinted/NotoSansBalinese-Regular.ttf](https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSansBalinese-Regular.ttf) hasn’t been updated since September 2015, and the version at [alpha/from-pipeline/unhinted/ttf/sans/NotoSansBalinese-Regular.ttf](https://github.com/googlei18n/noto-fonts/blob/master/alpha/from-pipeline/unhinted/ttf/sans/NotoSansBalinese-Regular.ttf) has only glyph changes and is even missing the GDEF and GPOS tables.

Where can I find the updated version of the font with the fix?

**Comment by behdad** [comment]
@marekjez86 see Norbert's last message.  Were the fixes ever delivered?

**Comment by behdad** [comment]
Same question re Javanese.  Is there a delivery coming or it's frozen.
