### ISSUE TITLE
Automatic Arabic ligatures

### ISSUE THREAD

**Issue by shawnl** [googlei18n/noto-fonts#411]
https://en.wikipedia.org/wiki/Arabic_script_in_Unicode#Word_ligatures

The above ligature presentation forms were deprecated by the most recent UNICODE version, (and these ligatures are in common usage) however no existing fonts automatically combine these series of code-points into ligatures. (Actually Amiri appears to combine Allah/الله)

Either Noto should include these presentation form code-points (as these ligatures are in very common use), or the font should be sophisticated enough to render the ligatures automatically when the NFKD form for them is found.

**Comment by khaledhosny** [comment]
The Arabic Presentation Forms have been deprecated for a long time (probably since the day they were encoded as they are compatibility characters), I doubt that they are in common usage by any measure. Fonts like Amiri has many “ligatures<sup>(1)</sup>” because the style of the font requires them, but they are unrelated to those encoded characters, and simplified designs like Noto Arabic Naskh do not need them most of time (though I personally thing it can make use of some contextual alternates especially around final Yeh, but that is a different matter).

<sup>(1)</sup> Amiri does not actually include any ligatures, it has contextual alternates for specific combinations.

**Comment by shawnl** [comment]
While the code-points are not common, the ligatures are. Without ligatures(1) provided by the fonts, applications will continue to use images for this purpose, which is non-optimal.

(1)or contextual alternatives

**Comment by khaledhosny** [comment]
Do you have examples of such use on the wild?

**Comment by shawnl** [comment]
http://www.mujahideenryder.net/pdf/WhoAretheDisbelievers.pdf

https://www.reddit.com/r/islam/ (see right side-bar)

p.1 of the Arabic-English Al-Ghazali's The Incoherance of the Philosophers, translated by Michael Marmura, BYU (a wide ﷽)

Mostly religious stuff with ﷺ/صلى الله عليه وسلم

**Comment by khaledhosny** [comment]
Noto Arabic Naskh already has ﷺ, so what you is missing is only a wide ﷽, since other symbols in your examples don’t have Unicode points at all.

**Comment by shawnl** [comment]
OK. So then Unicode should make these characters subject to canonical decomposition, rather than compatibility decomposition. http://www.unicode.org/reports/tr15/ Where can I file that bug?

How did you do a footnote in markdown when you closed the bug?

**Comment by brawer** [comment]
> Unicode should make these characters subject to canonical decomposition, rather than compatibility decomposition.  [...] Where can I file that bug?

http://www.unicode.org/reporting.html

**Comment by behdad** [comment]
> So then Unicode should make these characters subject to canonical decomposition, rather than compatibility decomposition.

No.  You are wrong.  Those characters don't need to be in Unicode.  Ligatures are formed out of glyphs.  Just listen to whatever Khaled says.  He knows what he's saying.
