### ISSUE TITLE
Latin: U+02DE RHOTIC HOOK attachment to ə and ɑ is respectively too low and too high

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#436]
Moved from googlei18n/noto-alpha#261 

Imported from [Google Code issue #261](https://code.google.com/a/google.com/p/noto-alpha/issues/detail?id=261) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-10-26T02:48:47.000Z:

---

U+02DE RHOTIC HOOK attachment to ə and ɑ is respectively too low and too high 

Compare the rendering of the sequence &quot;ə˞ a˞ ɑ˞&quot; in Noto Sans, Noto Serif, and Cambria. Also compare with examples on pages ix and 16 of the IPA handbook.

![noto-sans](https://cloud.githubusercontent.com/assets/12721521/8660020/56590a32-2963-11e5-8176-20a3ff6fd1f4.png)
![noto-serif](https://cloud.githubusercontent.com/assets/12721521/8660021/56596310-2963-11e5-9216-65d84a83417e.png)

![cambria](https://cloud.githubusercontent.com/assets/12721521/8660022/565e9088-2963-11e5-8d5c-7a7d3245f18e.png)

**Comment by jungshik** [comment]
Moreover, the shape of U+02DE attached to ə seems to be wrong.

**Comment by jungshik** [comment]
@tiroj made this comment back in December:

The rhotic hook should be applied at a common height, and I recommend handling it as a spacing 
glyph, not a zero-width mark, and attaching it using kerning or cursive attachment. Note that as 
implemented in the Noto fonts, it collides with following letters: a˞
determined by the position of the rhotic hook in the precomposed schwa combination ɚa˞h ɚa˞h
(the stylised ɚ in which the crossbar of the schwa angles up into the rhotic hook derives from 
phoneticists’ handwriting, and isn’t obligatory).

In the two precomposed rhotic vowels, 025A and 025D, the hook should extend further on the 
right side of the letter: ɚɝ ɚɝ

**Comment by jungshik** [comment]
![bug436 sans](https://cloud.githubusercontent.com/assets/8578343/9589383/cb7f631a-4fe2-11e5-98ef-a32ed22da4cb.png)

The above is what I got from a new version of Noto Sans LGC (built with glyphs) for "ə˞ a˞ ɑ˞". They look good, but I also need to check what @tiroj mentioned in the comment above (26 days ago).

**Comment by jungshik** [comment]
![bug436 sans](https://cloud.githubusercontent.com/assets/8578343/9618139/4e65743c-50b9-11e5-888f-0959531908c0.png)

1st line : "U+0259 (ə)  U+02DE",  "a U+02DE",  " ɑ U+02DE",  "ɜ U+02DE"
2nd line : h is appended to see how U+02DE is behaving  (if there's an collision)
3rd line : ɚh ɝh
 (ɚ U+025A = "precomposed" form for U+0259 + 02DE , 
   ɝ : U+025D = "precomposed" form for U+025C + 02DE. )

**Comment by jungshik** [comment]
We may need a new bug against the shape of U+025D and U+025C + U+02DE.

BTW, is it all right for the shape of u+025A to be different from the shape of U+0259 + U+02DE  (the 1st glyph in line 2 and line 3).

**Comment by tiroj** [comment]
Yes, I would recommend redesign of U+025D; at present it isn't clear that this is rhotic hook and the shape should be more consistent with the other rhoticised letters.

As noted in my earlier comments, the treatment of rhoticised schwa with diagonal bar is derived from linguists' handwriting. It isn't a requirement of the glyph, and I think a typographic treatment that preserves the regular shape of the schwa is appropriate here.

**Comment by moyogo** [comment]
The two letters ɚ U+025A and ɝ U+025D were used in IPA before the rhotic hook was adopted as a diacritic/modifier letter. They were proposed as IPA symbols in 1939 by the editors of the journal *American Speech*. It took a while for them to be adopted as the IPA preferred to have new diacritics for colouring instead of new symbols. The IPA adopted the right hook and the superscript turned r for r-coloured vowels before ɚ U+025A appears in the 1952 IPA chart (only ᶕ is in the 1947 IPA chart along with ᶒ, ᶏ, ᶗ, etc., eɹ, etc. and eʴ, etc.).
The right hook (ᶒ, ᶏ, ᶗ, etc.) was dropped from IPA in 1976.

After the 1989 Kiel Convention, the hook of ɚ U+025A and ɝ U+025D was adopted as the rhotic hook ˞ U+02DE for r-coloured vowels, a ə˞ with a horizontal stroke is used in the IPA chart since. According to Pullum (1990) in the *Journal of the International Phonetic Association*, ˞ U+02DE doesn’t have to be attached (in fact he says it shouldn’t be), this is reflected in the Unicode chart with the note: often ligated: 025A ɚ  = 0259 ə  + 02DE ˞ ; 025D ɝ  = 025C ɜ  + 02DE ˞.

ɚ U+025A and ɝ U+025D don’t have to look exactly the same as ə˞ (U+0259 + 02DE) and ɜ˞ (U+025C + 02DE), since the first two are letters and the last two are letters with diacritics/modifier letters.
ɚ U+025A should have a diagonal stroke if it is intended to represent the letter that was proposed in 1939 and used before the adoption of the diacritic/modifier letter rhotic hook in 1989.
I don’t think IPA users are aware of this historical distinction between the letters and the rhotic hook diacritic, so a difference in glyphs would only be useful when discussing that very distinction.

**Comment by marekjez86** [comment]
all fonts look good in the following test
```html
<html lang="en">
	<p style="font-weight:700"> "ə˞ a˞ ɑ˞"</p>
</html>
```

[en-436-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677984/en-436-NotoSans-Black.pdf)
[en-436-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677985/en-436-NotoSans-Italic.pdf)
[en-436-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677986/en-436-NotoSans-Regular.pdf)
[en-436-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677988/en-436-NotoSansDisplay-Black.pdf)
[en-436-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677987/en-436-NotoSansDisplay-Italic.pdf)
[en-436-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677989/en-436-NotoSansDisplay-Regular.pdf)
[en-436-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677994/en-436-NotoSansMono-Black.pdf)
[en-436-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677990/en-436-NotoSansMono-Regular.pdf)
[en-436-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677991/en-436-NotoSerif-Black.pdf)
[en-436-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677993/en-436-NotoSerif-Italic.pdf)
[en-436-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677992/en-436-NotoSerif-Regular.pdf)
[en-436-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677995/en-436-NotoSerifDisplay-Black.pdf)
[en-436-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678000/en-436-NotoSerifDisplay-Italic.pdf)
[en-436-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677997/en-436-NotoSerifDisplay-Regular.pdf)
[en-436-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677996/en-436-Roboto-Black.pdf)
[en-436-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677999/en-436-Roboto-Italic.pdf)
[en-436-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677998/en-436-Roboto-Regular.pdf)
