### ISSUE TITLE
Tai Le: Combining diacritics are missing from the font

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/noto-fonts#472]
moved from https://github.com/googlei18n/noto-alpha/issues/243

Imported from [Google Code issue #243](https://code.google.com/p/noto-alpha/issues/detail?id=243) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-06-14T01:33:00.000Z:

----
The traditional Tai Le orthography uses the following five combining characters as tone marks, but they are missing from the Noto Sans Tai Le font: U+0300, U+0301, U+0307, U+0308, and U+030C.

GPOS and GSUB information should also be added to the font to position the characters properly. Also note that the Unicode standard specifies that &quot;When one of the combining diacritics follows a tall letter [...], it is displayed to the right of the letter, [...]&quot; basically becoming spacing.

See http://www.unicode.org/L2/L2001/01369-n2372.pdf and section 11.5 of Unicode Standard version 6.2 (http://www.unicode.org/versions/Unicode6.2.0/ch11.pdf).

**Comment by jungshik** [comment]
/cc @kmansourMT 

googlei18n/nototools#62 deals with a lint tool addition for checking this.

**Comment by dougfelt** [comment]
The current version is 1.03.
The diacritics are in the font and position ok over ka:
![taile](https://cloud.githubusercontent.com/assets/9939212/10260689/dde6afca-692f-11e5-869c-913aaefb7909.png)

They also position to the right of tall letters.  However, they seem to swallow (overhang?) the spaces that follow them (each of these except the last is followed by space):
![taile2](https://cloud.githubusercontent.com/assets/9939212/10260692/f7790dc0-692f-11e5-8f88-e6065dfaf053.png)

The referenced document (and the bug report) mention that combining diacritics should become spacing marks "Typographically, when one of the combining diacritics follows a tall letter, it is represented as a spacing mark." (http://www.unicode.org/L2/L2001/01369-n2372.pdf) but it seems the generated mark is not spacing:
![taile4](https://cloud.githubusercontent.com/assets/9939212/10260739/7dd20e48-6931-11e5-9c82-d542d1866222.png)

Notice how in each case (except the last, where there is no following consonant) the mark overhangs the following consonant ka, instead of turning into a spacing mark.

So this is not yet fixed.

**Comment by kmansourMT** [comment]
Please point us to your font data and text files.
Thanks.

**Comment by kmansourMT** [comment]
I've run some tests to verify the reported errors and have found the following.
The attached test file (TaiLe-test-03xx.txt) was rendered through 3 separate OT interpreters: Harfbuzz, Uniscribe (thru Babelpad), and Monotype's PFC. The shaper output from Harfbuzz indicates that the spacing versions of the marks have been selected, but the PDF shows the marks overlaying the successive base character. Both BabelPad and PFC correctly show spacing marks in their rendering. See attached files. 

![taile-test-03xx-pfc](https://cloud.githubusercontent.com/assets/12738181/10296927/270297b0-6b82-11e5-983a-c26a5e00a97e.png)
![taile-test-03xx-babelpad](https://cloud.githubusercontent.com/assets/12738181/10296928/270334ae-6b82-11e5-83f1-548c5bbe552f.png)

**Comment by kmansourMT** [comment]
![taile-test-03xx-hb](https://cloud.githubusercontent.com/assets/12738181/10297044/2106689a-6b83-11e5-833d-50f86a2b274b.png)

**Comment by dougfelt** [comment]
I was using hb-view to generate the images that I posted, so perhaps there is a HarfBuzz issue.  @behdad?

**Comment by behdad** [comment]
@jfkthame.  Do you have any suggestions here?  The issue seem to be that for Tai Le and many other scripts, if we don't send them through USE shaper, they go through default, which has HB_OT_SHAPE_ZERO_WIDTH_MARKS_DEFAULT, which is to zero mark advances.

**Comment by behdad** [comment]
I can add a version of default shaper that doesn't zero marks, but not clear to me which scripts should go through it.  Perhaps those that Uniscribe implements?

**Comment by marekjez86** [comment]
I'm not sure if this should be assigned to waksmonskiMT at this point.

**Comment by dougfelt** [comment]
Not sure why @behdad didn't take it, but I agree it doesn't seem like an MTI issue.

**Comment by kmansourMT** [comment]
I would like to reiterate that the spacing versions of the combining marks u0300, u0301, u0307, u0308, and u030C are not classified as marks, but as bases. In the contexts where a tall vowel interferes with the placement of combining marks, we explicitly substitute the non-spacing mark with a spacing base glyph. There is therefore good reason to believe that this is a HarfBuzz error.

**Comment by behdad** [comment]
This should be fixed in HarfBuzz master.  Release will come in a few days.
