### ISSUE TITLE
Prime symbols not angled

### ISSUE THREAD

**Issue by aaaxx** [googlei18n/noto-fonts#510]
- U+2032 prime
- U+2033 double prime
- U+2034 triple prime

Used for representing feet and inches, and minutes and seconds.

Right now (v1.05) they're straight and look the same as straight quotes and apostrophe. But generally they are designed slightly angled to the right.

Is this intentional or just an oversight?

Some info on design: https://www.microsoft.com/typography/developers/fdsspec/symbol.aspx

**Comment by moyogo** [comment]
It is more common to have ′″‴ 2032 2033 2034 with a slant, different from '" 0027 0022. Especially since the are flipped in ‵‶ 2057 2035, which might be supported at some point. There’s also the modifier letters ʹʺ 02B9 02BA which are used in transliteration of Cyrillic and Hebrew script and q⁗ 2057, that should follow similar design. In some fonts ʹʺ 02B9 02BA are upright and look like '" 0027 0022 but that doesn’t seem right.

This is with Arimo, Cousine, Tinos, Noto Sans, Noto Serif: ′1″1‴1⁗1ʹ1ʺ1‵1‶1‷1'1" 0031 2032 0031 2033 0031 2034 0031 2057 0031 02B9 0031 02BA 0031 2035 0031 2036 0031 2037 0031 0027 0031 0022
![screen shot 2015-09-08 at 20 48 33](https://cloud.githubusercontent.com/assets/1923747/9745631/07b2d0d6-566b-11e5-9289-8390d503a852.png)

In Arimo:
* the modifier letters ʹʺ 02B9 02BA should be like ′″ 2032 2033 (they could be slightly different) instead of being like '" 0027 0022.

In Cousine:
* the modifier letters ʹʺ 02B9 02BA should be like ′″ 2032 2033 (they could be slightly different) instead of being like '" 0027 0022 ;
* ⁗ ‵‶‷ 2057 2035 2036 2037  are not there.

In Tinos:
* the glyphs are as expected;
* ʹʺ 02B9 02BA and ′″ 2032 2033 could be slightly different.

In Noto Sans and Noto Serif:
* the modifier letters ʹʺ 02B9 02BA have the expected shape in Noto Sans and Noto Serif, ′″‴ 2032 2033 2034 should follow their design (they could be slightly different) instead of being like '" 0027 0022 ;
* ⁗ ‵‶‷ 2057 2035 2036 2037 are not there.

**Comment by moyogo** [comment]
Given the shape the apostrophe/single quotation mark and the double quotation mark, the upright shape of prime and double prime is probably intentional in Noto Sans.
![screen shot 2015-09-09 at 07 29 57](https://cloud.githubusercontent.com/assets/1923747/9754831/9d9ae6ac-56c4-11e5-8ed1-9fde5d42d8aa.png)

**Comment by moyogo** [comment]
To avoid ambiguity, it’s usually better to have the following:
* ||-shape: ASCII quotes, saltillo;
* 9-shape and 6-shape: apostrophe, comma, typographic quotes;
* //-shape and \\\\-shape: prime and reversed prime.

In Noto Serif, the comma and apostrophe have a 9-shape that allows the prime to have a //-shape instead of a ||-shape.
In Noto Sans, the comma and apostrophe have a //-shape so the prime is always going to be problematic.

**Comment by xiangyexiao** [comment]
@SteveMatteson, please provide comment on whether the current shape of the three prime symbols are in Noto Sans and Serif are intentional or not. 
U+2032 prime
U+2033 double prime
U+2034 triple prime

It seems they should be slanted to left a bit to be different from apostrophe (0027) and double quotation mark (0022)

**Comment by SteveMatteson** [comment]
These are supposed to be vertical. Also Unicode defines 0022 as same as ‘double prime’ … these are not supposed to slant (or curl) like apostrophes.
Steve

On Feb 28, 2016, at 1:56 PM, Xiangye Xiao <notifications@github.com<mailto:notifications@github.com>> wrote:


@SteveMatteson<https://github.com/SteveMatteson>, please provide comment on whether the current shape of the three prime symbols are in Noto Sans and Serif are intentional or not.
U+2032 prime
U+2033 double prime
U+2034 triple prime

It seems they should be slanted to left a bit to be different from apostrophe (0027) and double quotation mark (0022)

**Comment by xiangyexiao** [comment]
In Arial and Helvetica, the prime symbols are slanted to left. Meanwhile single quotation mark 0027 and double quotation mark 0022 are 6-shaped or 9-shaped.

<img width="1023" alt="screen shot 2016-02-29 at 3 03 07 pm" src="https://cloud.githubusercontent.com/assets/12721521/13412064/958a0e20-def5-11e5-9689-cea62085605d.png">

**Comment by SteveMatteson** [comment]
There is no ‘right’ answer for these. Prime marks are the same shape as symmetrical quotes (ascii) in many fonts and unicode says they can be the same. The quotes you refer to as 6 and 9  shaped below are coming up the way you show because ‘smart quotes’ are being substituted in your word processor.

Since prime can correctly be straight or slanted just tell me what Google wants and we’ll do it.

On Feb 29, 2016, at 4:07 PM, Xiangye Xiao <notifications@github.com<mailto:notifications@github.com>> wrote:


In Arial and Helvetica, the prime symbols are slanted to left. Meanwhile single quotation mark 0027 and double quotation mark 0022 are 6-shaped or 9-shaped.

[screen shot 2016-02-29 at 3 03 07 pm]<https://cloud.githubusercontent.com/assets/12721521/13412064/958a0e20-def5-11e5-9689-cea62085605d.png>

**Comment by xiangyexiao** [comment]
there seems to be two options.
1. keep current behavior
2. make the three prime symbols slanted to left, and change the quotes to be 6 and 9  shaped (when used as smart quotes). We cannot only do the change for primes because it will make primes and quotes too similar to each other.

Considering both are correct, and option 1 is easy, I prefer to keeping the current behavior unless others don't agree.

@jungshik @marekjez86 @dougfelt @roozbehp

**Comment by marekjez86** [comment]
Agree with "keeping the current behavior"

**Comment by SteveMatteson** [comment]
thank you - I would hate to change it and have people ask for it back the other way :-)
all the best
Steve Matteson
Creative Type Director
_________________________
1048 Meadow Court
Louisville, CO 80027
_________________________
303 588 9755
_________________________
monotype.com/Studio<http://monotype.com/Studio>

On Feb 29, 2016, at 6:43 PM, Marek Jeziorek <notifications@github.com<mailto:notifications@github.com>> wrote:


Agree with "keeping the current behavior"

**Comment by roozbehp** [comment]
Considering @xiangyexiao's [comment](https://github.com/googlei18n/noto-fonts/issues/510#issuecomment-190440267) that looks at the behavior of Microsoft fonts, Microsoft's recommendation at https://www.microsoft.com/typography/developers/fdsspec/symbol.aspx, that Unicode's glyphs for these are slanted top-right to bottom-left, that I could not find any reference in Unicode about what @SteveMatteson was mentioning about Unicode recommendation (he said Unicode was saying that prime marks and ASCII quotes potentially being the same shape, but I can't find any such information in the Unicode standard), and that these three characters have clear usage in mathematics that has them slanted, it's clear to me that the existing glyphs are wrong and that we at Android definitely need the glyphs for U+2032..U+2034 slanted. If the fonts also support U+2035..U+2037, those would need to be mirror images of these.

The ambiguity with other characters not an issue for us. So many Unicode characters look similar. So there's no need to change any glyphs other than the three to six I mentioned at the end of the above paragraph.

/cc @raphlinus

**Comment by xiangyexiao** [comment]
Based on the reference given by Roozbeh (https://github.com/googlei18n/noto-fonts/issues/510#issuecomment-192063010), the three prime symbols U+2032..U+2034 in Noto {Sans, Serif} x {Roman, Italic} should be slanted to left 75..80 degrees in both roman and italic fonts. 
<img width="1063" alt="screen shot 2016-03-07 at 5 48 31 pm" src="https://cloud.githubusercontent.com/assets/12721521/13589449/da670fb0-e48c-11e5-8c09-2df69dc6b406.png">

The three reversed prime symbols U+2035..U+2037 in Noto {Sans, Serif} x {Roman, Italic} are slanted to right, but they are not mirrored glyphs as U+2032..U+2034 in Noto {Sans, serif} Italic. 

@SteveMatteson Please fix this issue in Phase 3 fonts. In the four families  Noto {Sans, Serif} x {Roman, Italic}:
- U+2032..U+2034 should be slanted to left
- U+2035..U+2037 should be mirrored images of U+2032..U+2034

**Comment by xiangyexiao** [comment]
Hi Marek, Monotype has fixed the issue on P3 fonts. could you generate TTF fonts from the P3 sources and pass them to Jungshik?

**Comment by jungshik** [comment]
JFYI:

I got confused by the screenshot included in https://github.com/googlei18n/noto-fonts/issues/510#issuecomment-193552402 
v2 Noto Serif does not cover any of reverse primes (U+2035 ~ U+2037).

**Comment by jungshik** [comment]
This is blocked by googlei18n/fontmake#50. I transplanted glyphs without scaling and for the obvious reason, it does not work.

**Comment by jungshik** [comment]
Just for the record, I scaled 3 prime glyphs myself (1000 upem => 2048 upem) and transplanted them to Noto Serif v2 (unhinted) from Noto Serif v3 ttf generated from Monotype's latest source files.

**Comment by davelab6** [comment]
Just curious, which font editor did you use for this? :)

**Comment by jungshik** [comment]
I considered using fontTools to scale glyphs but found it quicker to just edit the ttx output with my quick and dirty Python script and merge the edited result back.  BTW, in this particular case, all the contours in glyphs to scale are made of straight lines so that I don't have to worry about other complications. Obviously, what I did cannot be generalized.  For that, we have to wait for googlei18n/fontmake#50. :-)

**Comment by jungshik** [comment]
Copying from the bug report:  

In Arimo:
the modifier letters ʹʺ 02B9 02BA should be like ′″ 2032 2033 (they could be slightly different) instead of being like '" 0027 0022.

In Cousine:
the modifier letters ʹʺ 02B9 02BA should be like ′″ 2032 2033 (they could be slightly different) instead of being like '" 0027 0022 ;
⁗ ‵‶‷ 2057 2035 2036 2037 are not there.

Have Arimo and Cousine been fixed as well (see the above)?  @SteveMatteson , @waksmonskiMT @TrueTyper

**Comment by marekjez86** [comment]
Arimo delivered on 22/Mar (lower line)
[aArimo-prime.pdf](https://github.com/googlei18n/noto-fonts/files/260475/aArimo-prime.pdf)
Cousine delivered on 22/Mar (lower line)
[aCousine-prime.pdf](https://github.com/googlei18n/noto-fonts/files/260476/aCousine-prime.pdf)
Tinos delivered on 22/Mar (lower line)
[aTinos-prime.pdf](https://github.com/googlei18n/noto-fonts/files/260477/aTinos-prime.pdf)

**Comment by marekjez86** [comment]
This bug is from now on used ONLY for Noto issues. For Arimo, Cousine or Tinos issues please see https://github.com/googlei18n/noto-fonts/issues/687 .

Since I created bug https://github.com/googlei18n/noto-fonts/issues/687 to track Arimo, Cousine or Tinos issues, I'm removing the ArimoTinosCousine label here.

**Comment by marekjez86** [comment]
Kat, could you ask someone to check
https://github.com/googlei18n/noto-fonts/blob/master/alpha/OTF/from-pipeline/NotoSansUI-Regular.otf
https://github.com/googlei18n/noto-fonts/blob/master/alpha/OTF/from-pipeline/NotoSansMono-Regular.otf
https://github.com/googlei18n/noto-fonts/blob/master/alpha/OTF/from-pipeline/NotoSansDisplay-Regular.otf
https://github.com/googlei18n/noto-fonts/blob/master/alpha/OTF/from-pipeline/NotoSerif-Regular.otf
https://github.com/googlei18n/noto-fonts/blob/master/alpha/OTF/from-pipeline/NotoSerifDisplay-Regular.otf
https://github.com/googlei18n/noto-fonts/blob/master/alpha/OTF/from-pipeline/NotoSansDisplay-RegularItalic.otf
https://github.com/googlei18n/noto-fonts/blob/master/alpha/OTF/from-pipeline/NotoSansUI-Italic.otf
https://github.com/googlei18n/noto-fonts/blob/master/alpha/OTF/from-pipeline/NotoSerif-Italic.otf

to see if 
U+2032..U+2034 are slanted to left
U+2035..U+2037 are mirrored images of U+2032..U+2034
?

Thanks

**Comment by TidharC** [comment]
Here are the results for the 8 fonts above:

![primesslant](https://cloud.githubusercontent.com/assets/16353803/19991642/5db59e84-a1f4-11e6-92eb-07c4e1979705.png)

**Comment by marekjez86** [comment]
test
```html
<html lang="en">
<p><span style="font-size:48.0px">′ ″ ‴ ⁗ ‵ ‶ ‷</span></p>
</html>
```

Noto fonts look fine (they are all consistent), but ( @jamesgk ) Roboto prime and double-prime have problems (see below).

![roboto-primes](https://cloud.githubusercontent.com/assets/13322623/21626517/6adf0008-d1c6-11e6-93f1-dc9b563ee8e0.jpeg)


all results

[en-510-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683475/en-510-NotoSans-Black.pdf)
[en-510-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683474/en-510-NotoSans-Italic.pdf)
[en-510-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683476/en-510-NotoSans-Regular.pdf)
[en-510-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683473/en-510-NotoSansDisplay-Black.pdf)
[en-510-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683471/en-510-NotoSansDisplay-Italic.pdf)
[en-510-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683472/en-510-NotoSansDisplay-Regular.pdf)
[en-510-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683482/en-510-NotoSansMono-Black.pdf)
[en-510-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683477/en-510-NotoSansMono-Regular.pdf)
[en-510-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683481/en-510-NotoSerif-Black.pdf)
[en-510-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683478/en-510-NotoSerif-Italic.pdf)
[en-510-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683480/en-510-NotoSerif-Regular.pdf)
[en-510-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683479/en-510-NotoSerifDisplay-Black.pdf)
[en-510-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683483/en-510-NotoSerifDisplay-Italic.pdf)
[en-510-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683484/en-510-NotoSerifDisplay-Regular.pdf)
[en-510-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683485/en-510-Roboto-Black.pdf)
[en-510-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683486/en-510-Roboto-Italic.pdf)
[en-510-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683487/en-510-Roboto-Regular.pdf)

**Comment by jamesgk** [comment]
Roboto issue exists at https://github.com/google/roboto/issues/161
