### ISSUE TITLE
Latin and cyrillic glyph X render issue in Noto Serif Italic

### ISSUE THREAD

**Issue by vnh19** [googlei18n/noto-fonts#515]
Starting in September 2015 there is a render issue with glyph X in Noto Serif Italic...
![googlefont_noto_serif_italic](https://cloud.githubusercontent.com/assets/13781646/9870027/3fe06d44-5b91-11e5-863a-fb7ed281090a.JPG)

**Comment by dougfelt** [comment]
I'm not able to reproduce this using my installed version of NotoSerif-Italic and the create_image tool.  Perhaps it is specific to the web version.

**Comment by roozbehp** [comment]
@dougfelt, this may be due to hinting issues. Does create_image use hints?

**Comment by dougfelt** [comment]
Duh, let me try using .png output.

**Comment by davelab6** [comment]
I reproduced this. This must have been introduced in https://github.com/google/fonts/commit/40e62b2bcec0cefb20029f5cabcc2daf884db21e when I updated to 1.04. 
![screen shot 2015-09-15 at 19 24 46](https://cloud.githubusercontent.com/assets/261579/9892718/7d05188e-5bdf-11e5-8869-1894c06866d8.png)

**Comment by dougfelt** [comment]
I can't reproduce this on google fonts using chrome on linux.  Would my platform matter?

**Comment by jungshik** [comment]
@davelab6 : platform and browser (version) information?

**Comment by davelab6** [comment]
Its Win 8 (corp vm) with Chrome Version 45.0.2454.85; we rerolled it back so it may no longer appear for you, although I still see it here in a cafe in NYC

**Comment by codeman38** [comment]
This is a duplicate of bug #270, which I filed back when the repo was still on Google Code.

**Comment by jungshik** [comment]
> watch out for having the fonts installed locally, as if installed they will be used instead of the API fonts

We did (Doug and Stuart removed their local copies so that the font from the web font is used) and couldn't reproduce the problem.  It could be explained by what @davelab6 wrote (corp which already has a revert vs public where the revert is not yet in effect). 

However, we couldn't reproduce the problem even with the latest Noto Serif and hb-view. That is, Noto Serif in repo should be fine. 

It looks like something happened when you put Noto Serif in the Google Font directory. 

Another possibility is that the latest Noto Serif has a problem with hint instructions, which would only manifest itself on Windows when tested as a Web font. 

I'll try freetype to see if there's a problem because I can control whether or not to use hints with FT. I'll also try the latest version (that was in the Google FOnt directory but reverted) on Windows.

**Comment by jungshik** [comment]
@davelab6 
> we rolled it back to the previous version

What version did you roll back to? Can you give me a version number so that I can compare that version with the latest ?

**Comment by jungshik** [comment]
I missed the comment by @codeman38. It looks like it's indeed a BCI issue in Noto Serif Italic. I'll double check (not that I don't believe @codeman38 but just in case) and dupe this bug to #270

**Comment by davelab6** [comment]
> What version did you roll back to?

Version 1.03

**Comment by jungshik** [comment]
Indeed, it's a BCI hint issue. See the screenshots below (Noto Serif Italic) 

With BCI hint ON : 
![image](https://cloud.githubusercontent.com/assets/8578343/9912487/bc1d57de-5c5c-11e5-800d-61c162ac14eb.png)

With Hint OFF: 
![image](https://cloud.githubusercontent.com/assets/8578343/9912504/cb787632-5c5c-11e5-9872-5c81036276cd.png)

With FT's autohint

![image](https://cloud.githubusercontent.com/assets/8578343/9912532/fa35d38e-5c5c-11e5-8dfe-3f1ddb909210.png)

**Comment by jungshik** [comment]
Duping to #270
