### ISSUE TITLE
Testing browser support for Noto Sans Bamum 

### ISSUE THREAD

**Issue by zenodotus** [googlei18n/noto-fonts#527]
Hi, 

This link is displaying Bamum script successfully on Chrome, IE, and FF in Windows 7:
http://andrewc.vicnet.net.au/test/bamum/bamum-test.html

But when I paste the sample text (ꛖꚫꚨꚢꛃꚠꛤꚩ꛳) in on most pages, all that I see is empty boxes.  

Any idea how the Bamum script could be more widely supported across browsers and platforms?  It has been part of Unicode since version 6.0.

Regards,
Charles Riley

**Comment by jungshik** [comment]
The reason is  very simple. Andrew's test page uses a web font (Noto Sans Bamum) as served by Google Web Font ( http://www.google.com/fonts/earlyaccess). 

Unless you install Noto Sans Bamum (or any fonts supporting Bamum) on your local machine, a regular web page (that does NOT use a web font explicitly) would just show you Tofus (empty boxes). 

So, the best way is to use a web font when making a web page with Bamum script. That's one of reasons we make Noto Sans Bamum available via Google Web Fonts. Please, spread the words and use it on as many pages as possible :-).
