### ISSUE TITLE
Glyph design issue “ವು” (<U+0CB5, U+0CC1>) in Noto Kannada

### ISSUE THREAD

**Issue by MayuraVerma** [googlei18n/noto-fonts#535]
![screen shot 2015-10-24 at 8 38 05 pm](https://cloud.githubusercontent.com/assets/14062593/10713631/43871fd4-7a8f-11e5-8829-162ead854397.png)

![screen shot 2015-10-24 at 8 57 27 pm](https://cloud.githubusercontent.com/assets/14062593/10713676/e765d7a6-7a91-11e5-8279-172e6e033c52.png)

**Comment by jungshik** [comment]
@JelleBosmaMT : can you respond? Thanks

**Comment by MayuraVerma** [comment]
![screen shot 2015-10-25 at 8 40 25 am](https://cloud.githubusercontent.com/assets/14062593/10715886/12f6cb3e-7af4-11e5-96d0-0b44dfef8094.png)

**Comment by JelleBosmaMT** [comment]
In a "sans serif" style, notably in the bold, have a complete connection creates a blob, a dark spot. I do not see how it is possible to confuse the u with the subscript ra. The u starts at the baseline and the end almost touches the bottom of the consonant. At small sizes the gap is hardly visible. It embraces the consonant The ra starts at the baseline and the far end is as far away from the consonant as it possibly can be. It is at arms-length, which is the opposite of embracing. The are is different as can be and having a small gap, rather than a complete connection cannot make a difference.

**Comment by JelleBosmaMT** [comment]
They are as different as can be and having a small gap, rather than a complete connection cannot make a difference. (Github comment field auto-complete is evil.)

**Comment by JelleBosmaMT** [comment]
New attempt:
In a "sans serif" style, notably in the bold, have a complete connection creates a blob, a dark spot. I do not see how it is possible to confuse the u with the subscript ra. The u stroke starts at the x-height and the end almost touches the bottom of the consonant. At small sizes the gap is hardly visible. It embraces the consonant The ra starts at the baseline and the far end is as far away from the consonant as it possibly can be. It is at arms-length, which is the opposite of embracing. They are as different as can be and having a small gap, rather than a complete connection cannot make a difference.

**Comment by MayuraVerma** [comment]
@JelleBosmaMT thanks for making few ATTEMPTS to convince. (Very few people STARE at all the alphabets together and appreciate all the differences in the design. Most people install the fonts and start reading the content.) 

vu and vra very rarely occur together in same word to watch out for the difference in them. With noto kannada, when vu appears in word, it throws doubt in readers mind whether its vu or vra. First impression will be vra, because u is not connected to va. then reader will use his/her intuition based on the meaning of word to recognize its vu not vra. 

as far as the technical difficultly, "sans serif", "small gap", "x-height", "almost touches the bottom", "as it possibly can be", "arms length", "opposite of embracing",.... ordinary user CARES very little. 

NOTO KANNADA has a design flaw which changes the meaning of the word. Please recognize it and do the needful.

**Comment by JelleBosmaMT** [comment]
![countershape](https://cloud.githubusercontent.com/assets/12729011/10723383/a368b210-7bba-11e5-941a-42bdfc7b43ed.png)
Letterforms are made from black strokes. But within these are white shapes. Type designers know these white shapes matter as much and probably more than the strokes. The above image shows the white shapes of the normal u-vowel, the u-vowel variant for pa, ha and va, and finally the subscript ra. The u's are to the right of the consonant. The ra is completely below. Both u's connect to the consonant, the ra is completely open. That does not look very confusing to me.


In the Arial Unicode example, the stroke of the u connects with a very thin stroke to the pa, pha and va, in a place where these have thin strokes too. The style of the design is 'modulated'. There are distinct differences in thick and thin. But the Noto is 'Monoline". The strokes vary little in thick and thin, to make the font the equivalent of the Latin Noto Sans style. That means a thick stroke has to connect to two other thick strokes. There is not enough room to do that in a visually pleasing way. And the descending stroke of the pha will disappear in the bold weight.

![as is](https://cloud.githubusercontent.com/assets/12729011/10723508/ba51c682-7bbb-11e5-89bb-8a8d0517a692.png)
![connect](https://cloud.githubusercontent.com/assets/12729011/10723526/e799f394-7bbb-11e5-8b64-456ef9f52c1a.png)

**Comment by JelleBosmaMT** [comment]
At http://cdac.in/index.aspx?id=pdf_Kannada_TT%20fonts you can find a PDF
with a variety of Kannada fonts. The samples show a pu combination for
most of the designs. You will see that a “loose” u is quite common. For
example in Shruti and Smita, which are in the general style of Noto Sans
Kannada.

**Comment by MayuraVerma** [comment]
I again reiterate, from the reader perspective, vu looks like vra. it should be a simple test. Create a paragraph with few non-popular words with vu occurring in the paragraph. Let 10 users to read the paragraph and take their feedback. 

I showed the paragraph to 4 of friends, without giving any hints. They all stumbled on vu. I have also contacted a popular kannada daily newspaper. They had recognized even before I told them, that is one reason they are reluctant to switch to noto from tunga. Although tunga has other issues.

I will not fight this fight. No font is PERFECT. They are several reasons for fonts not being perfect, one of them is "RELUCTANCE to CHANGE or DEFENSIVE MINDSET". 

Thanks for the detailed explanation though.

**Comment by JelleBosmaMT** [comment]
"RELUCTANCE to CHANGE or DEFENSIVE MINDSET"

I am sorry, but I honestly cannot see how to confuse vra and vu or pra and pu or phra and pu. Please do not contribute this to a character flaw on my part. We all have character flaws, it is not a fruitful argument. For me it is very puzzling how something so different is perceived as too similar.

Incomprehensible.

The u is for at least 80 % to the right of the consonant and the ra for more than 80 % below. The long  vertical curve of u runs parallel and repeats the curve of pa, pha and va, which gives a very distinct effect. The short vertical curve of ra starts where the curve of the consonant ends.  That is very different. Go through the specimen of the C-DAC typefaces and with all the variation in shapes, the above is what the u’s and ra’s have in common and what makes them to what they are. And the rest differs from font to font. The majority does not connect. Personally I have no trouble telling them apart in any of these fonts. 

Is it possible that when learning to write, the difference is described  as “the u connects and the ra does not”? For handwriting that makes sense, because it is an inaccurate affair. A little bit too high or a little bit too low could create ambiguity, which can be prevented with a connection. A verbal description which sets itself in the mind is known to get in the way of the actual visual appearance. 

In the below I tried to make the “embrace” more firmly. Move the u slightly up and increase the length so it goes all the way up: aligning with the standard u-sign.  It increases the difference. Hopefully enough to tip the balance. I would like to avoid to have it look like Tunga. Left current Noto, right a possible new.

![poging](https://cloud.githubusercontent.com/assets/12729011/10798962/8258c334-7daa-11e5-89e2-f9358874e6b8.png)

PS: It has been a couple of years that I made the Noto Sans Kannada. But I remember having tried to connect the u. I tried and tried and it all looked hopeless out of style with the rest.

**Comment by lianghai** [comment]
@JelleBosmaMT:

Just a quick note here — mmm, I don't think you're trying on the correct/expected direction of change.

No, connecting isn't necessary, but generally the U-sign starts with a strong relationship to the bottom-center "crack" of ವ. Without that visual relationship, an U-sign looks detached from ವ.

Btw, you can see, most of those C-DAC fonts are shitty. However if you still can't figure out a way to connect the U-sign to ವ in this design, I think KN-Shruti's solution is a good reference — note the visual relationship around the start of the U-sign under ಪ.

As long as the U-sign doesn't connect to the base letter, there's always ambiguity. However usually the ambiguity is not a big deal.
But Noto Sans Kannada is meant to be a neutral-styled font, and the visual relationship in the current design of ವು is far from ideal, therefore native users get confused. Not being professional type designers, they tend to point out the problem is about connecting, but well, I guess it's not that straightforward.

Oops, just meant to write "a quick note" but ended up with this. Hope this comment helps anyway.

**Comment by JelleBosmaMT** [comment]
Taking KN-Shruti as inspiration I would get something like the variant on the right:

![poging 2](https://cloud.githubusercontent.com/assets/12729011/10830221/c0fab8de-7e7e-11e5-9f7e-d1d0eca1d550.png)

**Comment by MayuraVerma** [comment]
Order of preference
1. Connected (I know its not possible)
2. Right Version (first impression. Awesome. Still, will keep fingers crossed for different sizes and bold font)
3. Left Version.

Other similar characters needing attention for the same reason.

![screen shot 2015-10-29 at 7 09 35 pm](https://cloud.githubusercontent.com/assets/14062593/10835518/53720978-7e71-11e5-9417-314de0d0cae2.png)
![screen shot 2015-10-29 at 7 09 45 pm](https://cloud.githubusercontent.com/assets/14062593/10835517/5371b2d4-7e71-11e5-9a3c-28e77a8b6540.png)
![screen shot 2015-10-29 at 7 10 16 pm](https://cloud.githubusercontent.com/assets/14062593/10835519/53743b6c-7e71-11e5-89d1-1902c1b76c51.png)
![screen shot 2015-10-29 at 7 09 54 pm](https://cloud.githubusercontent.com/assets/14062593/10835516/5370f13c-7e71-11e5-8092-24dcae76f36e.png)

In case of pha, the vertical down stroke is not prominent. Please be generous with its depth. It is two short, in small font size, the vertical down stroke disappears.

Thank you for proposing the changes.

One more issue, I can open another issue for it or you can consider it in this issue.

There is kerning issue in the below characters
![screen shot 2015-10-29 at 7 11 06 pm](https://cloud.githubusercontent.com/assets/14062593/10835661/0dc27654-7e73-11e5-91cb-3a88e1673cec.png)
![screen shot 2015-10-29 at 7 11 13 pm](https://cloud.githubusercontent.com/assets/14062593/10835662/0dc35efc-7e73-11e5-8eff-2faf76b29552.png)
![screen shot 2015-10-29 at 7 31 00 pm](https://cloud.githubusercontent.com/assets/14062593/10835759/c8a62a56-7e73-11e5-9175-ee231061d15d.png)
![screen shot 2015-10-29 at 7 31 13 pm](https://cloud.githubusercontent.com/assets/14062593/10835758/c8a62768-7e73-11e5-89ff-141e2016ecbe.png)
![screen shot 2015-10-29 at 7 31 18 pm](https://cloud.githubusercontent.com/assets/14062593/10835761/c8a8a54c-7e73-11e5-9281-d72c9825854f.png)
![screen shot 2015-10-29 at 7 31 33 pm](https://cloud.githubusercontent.com/assets/14062593/10835762/c8a99042-7e73-11e5-886b-85137281224a.png)
![screen shot 2015-10-29 at 7 31 39 pm](https://cloud.githubusercontent.com/assets/14062593/10835760/c8a7f048-7e73-11e5-92bd-c3285749828a.png)

MANY MANY THANKS for trying resolve this issue.

PS:
As a font designer, I understand your technical limitations. If you stand in the shoes of the user/reader then you will acknowledge the issue easily. I understand it is very difficult to do so, when its not your native  language. Thats the reason, I proposed to take feedback from other native users (besides myself). You may have already done so, while designing the font!  

FYI: Kannada is not used extensively digitally due to several reasons. But people who use the font and recognize the issue, either doesn't know where n how to report it or care least(because they get used to it).

**Comment by lianghai** [comment]
> 1. Connected (I know its not possible)

It's far from "not possible".
It's just @JelleBosmaMT being way too conservative about optical adjustments in this design.

If the stroke is to get connected, then of course both the base (ವ, etc) and mark (U-sign, etc) glyphs need to be modified to make the connection legible and pretty. Trying to simply stick a longer U-sign to the default ವ glyph obviously won't work.

**Comment by JelleBosmaMT** [comment]
At the start of the project there was a focus group of native users in Google's employment, who looked at design proposals with variants. For Kannada and Telugu they steered me towards tight spacing, and subscripts marks close to the base glyphs in combination with large word spaces. (Unfortunately in Android spaces and punctuation are taken from the Latin Roboto font, unless a document request one of the Indic fonts by name.) After completion of the full set, the reviewers made me change some characters, but I received no comments about the alternate u and uu vowels.

The descender stroke in ಢ ಫ ಧ and so on is a puzzle. When used in UI there is a limit for the height. So the stroke has to be large enough to get noticed, but not so long it gets entangled with below base marks, which have to remain close to the base. Of course in Telugu the problem of overlaps with subscripts is larger than in Kannada. I guess the length and weight ratio of the stroke has to balance with the size of the dot that is used in some of the characters, taking into account that the dot is in a more prominent position, the stroke firmer than the dot. 

For the kerning issues, the combinations of  ಙ ಞ ಱ ೞ with  ೈ do not seem to exist apart from tables that show how consonants combine with vowels. At least in a list of Kannada words extracted from Wikipedia they appear 1 time as stand alone words only, and there probably exists such a table. But if it is OK to move the length-mark to be below and somewhat to the left of the e-mark, then I can do that without spending an extra contextual rule that a renderer will always have to check, but in practical terms will never be applied.

It is too late in the evening to comment about my (alleged) conservatism ;-)

**Comment by MayuraVerma** [comment]
@JelleBosmaMT Although Telugu is "Old Kannada" script. Let us not tie "Telugu-Old Kannada" with "Modern Kannada" script. If we can please solve the descender stroke in Kannada without bothering about Telugu, it will be great.

Regarding the Kerning issue, please do the needful. Even if we don't have Kannada words that uses characters, if Kannada people want to write other language words in Kannada, then it might handy. So, it hard to overlook any characters. Some Persian, Albanian, Korean, Chinese, ... song could become popular on TV, and a Kannada user wants to lyrics online, these characters might be used.

**Comment by lianghai** [comment]
@MayuraVerma:

> Although Telugu is "Old Kannada" script. Let us not tie "Telugu-Old Kannada" with "Modern Kannada" script.

No one is doing that.

**Comment by MayuraVerma** [comment]
Here is one good example of the "vu" issue. I had this article read by 5 Kannada people. This article has the word "sevuNara" third word in first line. It is not a common word, all were curious if it was "sevruNara". They didn't have problem reading other occurrences of "vu" in line 2 and 9 with common words.

I am doing my due diligence to convenience the needed change in the design.

Hopefully the change will come soon.

![screen shot 2015-11-01 at 1 59 09 am](https://cloud.githubusercontent.com/assets/14062593/10867664/e86c48c2-8033-11e5-94bf-3c420eef86b6.png)

**Comment by MayuraVerma** [comment]
One more live example of "pu" on www.prajavani.net. The word "puravaNi" can be easily mistaken to "praravaNi". It is using Noto Sans Kannada - Bold.

Issue confirmed with couple of native Kannada readers.

![screen shot 2015-11-03 at 9 45 20 pm](https://cloud.githubusercontent.com/assets/14062593/10929101/cba50470-8274-11e5-815a-9d73c8b5681c.png)

**Comment by JelleBosmaMT** [comment]
By now I am convinced that the alternate u is not clear enough. But it is
still mysterious why. To me it is almost like “this b looks too much like
a d” or something like that.

There are plans to re-release the Noto Sans Kannada with more weights. But
that will take a quite a while. Upgrading the existing fonts may make more
sense, although that is not going to happen overnight either. There is
regular and bold, hinted and unhinted, document and UI version: 8 fonts
that have to be updated, go through testing, delivery to Google. Then
Google has to do things too before it gets into the hands of users.

**Comment by MayuraVerma** [comment]
OK. I don't know how else convince. 

But your proposal "Taking KN-Shruti as inspiration I would get something like the variant on the right:" is a very convincing design.

![capture](https://cloud.githubusercontent.com/assets/14062593/10941764/80134554-82d2-11e5-81bc-6bd663e2ea1c.JPG)

Thanks for looking into this. If and when it get updated, it will be a big welcome.

**Comment by JelleBosmaMT** [comment]
![newknda u uukopie](https://cloud.githubusercontent.com/assets/12729011/11481599/8f819514-979e-11e5-9b45-84ce5488117c.png)

The updated characters would look like this. I hope this is OK.

In principle the fonts can be updated by replacing 4 glyphs: the u and uu glyphs that are used with p and v and the variants for ph. 

In due course the fonts will be re-released with additional weights, so the change can take place when this work is completed. But that is going to take a while. So it make sense not to wait and to update the existing fonts, without changing anything else other than the version numbers.
But this is a call that Google has to make, because it is through Google that the fonts are released.

**Comment by MayuraVerma** [comment]
It is wonderful to see the change. To say the least, it won't confuse readers for sure. 
As long as the change is coming at some point, wait will be worth.

**Comment by MayuraVerma** [comment]
Gentleman,

Any updates on the same?
When do can we see this implemented in the font?

thanks,
Mayura

**Comment by JelleBosmaMT** [comment]
It would have been nice to have released a quick update. But it has been decided to do this improvement as part of a project extending the fonts with additional weights. I am not sure where Kannada is in the order of priorities. But at least the minor hurdle Tamil and the major hurdle Bengali have to be taken first.

Best regards
Jelle
