### ISSUE TITLE
Mongolian GSUB does not support one standard variation sequence

### ISSUE THREAD

**Issue by dougfelt** [googlei18n/noto-fonts#542]
@roozbehp, you mentioned Mongolian in googlei18n/nototools#12. I've been developing a test for this, ran it on Mongolian, and there's one combination that doesn't seem to be supported:

Automatic testing for 'unhinted,NotoSansMongolian-Regular.ttf', Version 1.04 uh:
E Expected GSUB to generate all standard variants, but 1 cases did not (182d 180b (fina): [u182D.fin=0+1358|space=0+0])

There's a web site https://r12a.github.io/scripts/mongolian/variants that seems to indicate that this might be intentional-- NotoSansMongolian is one of the fonts examined on the site. I'm not sure how current the site is w.r.t. the version of StandardizedVariants.txt I'm using. Do you know anything about this site?

**Comment by brawer** [comment]
Would it be `GSUB` or a `cmap` type 14? (Probably doesn’t matter as long as the results are correct).

**Comment by roozbehp** [comment]
I have not followed the recent Mongolian issues very closely, so no idea about if the lack of the sequence in the font is intentional or not. @kmansourMT would know.

As for the website referenced, that is maintained by Richard Ishida, a very well-respected i18n expert who is part of a Mongolian task force at the W3C. I guess @r12a is his github handle.

Regarding the choice between GSUB and cmap type 14, there is a tradition that Mongolian fonts use GSUB, as far as I remember. HarfBuzz should work with both, but it's possible some layout engines may only support the GSUB version. /cc @behdad

**Comment by roozbeh** [comment]
@roozbehp I think you got this :-) I mentioned here because of my username being similar to yours :-)

**Comment by r12a** [comment]
@dougfelt the page at https://r12a.github.io/scripts/mongolian/variants shows glyph behaviour that may not yet be available in currently released versions of Mongolian Baiti, but i think it should represent actual observed behaviour (by me) for Noto Sans.

the page represents the outcome of discussions amongst Mongolian experts aimed at producing the next version of mongolian variant behaviours for StandardizedVariants.txt, since the current version of that has several issues, including both variance from actual font behaviour and the ability to represent what is needed for mongolian text.  The other aim of the discussions was to produce consensus among the various mongolian font developers as to what variants and sequences produce what glyphs.  The page reflects the consensus reached so far with the font developers involved in the discussion.

hope that helps

**Comment by KrasnayaPloshchad** [comment]
On BabelStone website I found another guide for design a Triditional Mongolian typrface. You can see here if you can read Chinese:

http://babelstone.co.uk/Mongolian/MGWBM.html

**Comment by behdad** [comment]
Mongolian uses GSUB for Mongolian variation selectors indeed.

**Comment by KrasnayaPloshchad** [comment]
> Mongolian uses GSUB for Mongolian variation selectors indeed.

That is nesessary, since Unicode Consortium have normalized the usage of Mongolian FVS. On current version of Mongolian code chart you can see the standard variations used FVS characters.

**Comment by marekjez86** [comment]
released https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansMongolian and https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansMongolian which should have the fixes
