### ISSUE TITLE
Wrong Cyrillic variations of letter К

### ISSUE THREAD

**Issue by ghost** [googlei18n/noto-fonts#578]
Cyrillic capital letters Қ, Ҝ, Ҟ and Ҡ should have Cyrillic base form (К), not Latin (K)

**Comment by jungshik** [comment]
@TrueTyper @SteveMatteson

**Comment by SteveMatteson** [comment]
the Sans Cyrillic K shape is being used for these characters…. compare to the Latin K.

[cid:188658E1-4922-4C21-980A-89205BC3ECBF@hsd1.co.comcast.net]

On Mar 23, 2016, at 3:41 PM, jungshik <notifications@github.com<mailto:notifications@github.com>> wrote:


@TrueTyper<https://github.com/TrueTyper> @SteveMatteson<https://github.com/SteveMatteson>

**Comment by roozbehp** [comment]
@vortaj is the bug in Noto Sans or Noto Serif or both?

**Comment by SteveMatteson** [comment]
The serif is also correct

On Mar 25, 2016, at 3:00 PM, Roozbeh Pournader <notifications@github.com<mailto:notifications@github.com>> wrote:


@vortaj<https://github.com/vortaj> is the bug in Noto Sans or Noto Serif or both?

**Comment by vortaj** [comment]
Just Sans. Serif is OK

**Comment by nizarsq** [comment]
Verifying in progress

**Comment by nizarsq** [comment]
Retested the issue with new Sans and Serif fonts, I can still see the same issue with the new Sans fonts, I am attaching some pdf files that shows the new Sans still have the base from (K) and Serif correct and the  base form (К). If I am understanding the issue correctly I belive this  issue still not fixed.
``<html lang="sr"> <p><span style="font-weight:700">Қ, Ҝ, Ҟ and Ҡ</span></p> </html>``
[NotoSans-Black-578.pdf](https://github.com/googlei18n/noto-fonts/files/623280/NotoSans-Black-578.pdf)
[NotoSansDisplay-Black-578.pdf](https://github.com/googlei18n/noto-fonts/files/623279/NotoSansDisplay-Black-578.pdf)
[NotoSansDisplay-Italic-578.pdf](https://github.com/googlei18n/noto-fonts/files/623278/NotoSansDisplay-Italic-578.pdf)
[NotoSans-Italic-578.pdf](https://github.com/googlei18n/noto-fonts/files/623277/NotoSans-Italic-578.pdf)
[NotoSerif-Black-578.pdf](https://github.com/googlei18n/noto-fonts/files/623276/NotoSerif-Black-578.pdf)
[NotoSerifDisplay-Black-578.pdf](https://github.com/googlei18n/noto-fonts/files/623275/NotoSerifDisplay-Black-578.pdf)
[NotoSerifDisplay-Italic-578.pdf](https://github.com/googlei18n/noto-fonts/files/623281/NotoSerifDisplay-Italic-578.pdf)
[NotoSerif-Italic-578.pdf](https://github.com/googlei18n/noto-fonts/files/623282/NotoSerif-Italic-578.pdf)
[OldNotoSerif-Italic-578.pdf](https://github.com/googlei18n/noto-fonts/files/623283/OldNotoSerif-Italic-578.pdf)

**Comment by marekjez86** [comment]
```html
<html lang="ru">
<p><span style="font-weight:700">cyrillic: К</span></p>
<p><span style="font-weight:700">Қ, Ҝ, Ҟ and Ҡ</span></p>
<p><span style="font-weight:700">latin K</span></p>
<p><span style="font-weight:700">Қ, Ҝ, Ҟ and Ҡ</span></p>
</html>
```
Sample for NotoSansDisplay-Black (check the latin K shape; then check the cyrillic K shape). The other cyrillic K-like letters are based cyrillic K not latin. It's possible that it didn't change because it was always correct :-) The way I see it it's possible it was juts fixed, or it was never an issue.

![cyr-k](https://cloud.githubusercontent.com/assets/13322623/20776316/a1443d24-b714-11e6-9328-560ca7a3092e.jpg)



Here's the output for generated by the fontdiff
[ru-578-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/623316/ru-578-NotoSans-Black.pdf)
[ru-578-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/623320/ru-578-NotoSans-Italic.pdf)
[ru-578-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/623317/ru-578-NotoSansDisplay-Black.pdf)
[ru-578-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/623318/ru-578-NotoSansDisplay-Italic.pdf)
[ru-578-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/623319/ru-578-NotoSerif-Black.pdf)
[ru-578-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/623321/ru-578-NotoSerif-Italic.pdf)
[ru-578-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/623322/ru-578-NotoSerifDisplay-Black.pdf)
[ru-578-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/623323/ru-578-NotoSerifDisplay-Italic.pdf)

**Comment by nizarsq** [comment]
I agree with @marekjez86. Thank you
