### ISSUE TITLE
Missing superscripts/subscripts

### ISSUE THREAD

**Issue by brawer** [googlei18n/noto-fonts#697]
In https://groups.google.com/forum/#!topic/noto-font/Pz5BrWRpgkw, it was reported that Noto does not fully cover [Superscripts and Subscripts](http://unicode.org/charts/PDF/U2070.pdf). I can confirm that Noto Sans v1.050 does not contain eg. U+2071.

**Comment by dougfelt** [comment]
Yes, this should have been covered, it's a Unicode 3.2 codepoint.  U+2071 will be in LGC and Mono for phase 3.  I'm not sure it's worth updating the phase 2 fonts separately, and once the phase 3 LGC is ready to go we should probably just push it instead, but we could copy the glyphs to fix things like this in the interim.

**Comment by jungshik** [comment]
I'd rather not bother to fix in Phase 2 (hoping that Phase 3 will be out soon).

**Comment by brawer** [comment]
Curious, why wasn’t this caught by the lint tools? (Entirely agree that U+2071 isn’t terribly important, but it would be good if the upcoming “Noto Phase 3” had full Unicode coverage.)

**Comment by dougfelt** [comment]
Phase 3 _does_ have full Unicode coverage.

For phase 2 lint only checked single fonts using sets of characters based
on their scripts plus custom data Roozbeh put together. When I started
checking total coverage in Jan (preparing to change how this was defined
for phase 3) we decided we could probably wait for phase 3 to cover these.

**Comment by nizarsq** [comment]
Verification in progress

**Comment by nizarsq** [comment]
This bug tested using new fonts and this issue is solved.
``<html lang="sr"> <p><span style="font-weight:700">&#8305;</span></p> </html>``
[NotoSans-Black-697.pdf](https://github.com/googlei18n/noto-fonts/files/622703/NotoSans-Black-697.pdf)
[NotoSansDisplay-Black-697.pdf](https://github.com/googlei18n/noto-fonts/files/622706/NotoSansDisplay-Black-697.pdf)
[NotoSansDisplay-Italic-697.pdf](https://github.com/googlei18n/noto-fonts/files/622704/NotoSansDisplay-Italic-697.pdf)
[NotoSans-Italic-697.pdf](https://github.com/googlei18n/noto-fonts/files/622705/NotoSans-Italic-697.pdf)
[NotoSerif-Black-697.pdf](https://github.com/googlei18n/noto-fonts/files/622707/NotoSerif-Black-697.pdf)
[NotoSerifDisplay-Black-697.pdf](https://github.com/googlei18n/noto-fonts/files/622708/NotoSerifDisplay-Black-697.pdf)
[NotoSerifDisplay-Italic-697.pdf](https://github.com/googlei18n/noto-fonts/files/622710/NotoSerifDisplay-Italic-697.pdf)
[NotoSerif-Italic-697.pdf](https://github.com/googlei18n/noto-fonts/files/622709/NotoSerif-Italic-697.pdf)
[OldNotoSerif-Regular-697.pdf](https://github.com/googlei18n/noto-fonts/files/622711/OldNotoSerif-Regular-697.pdf)
