### ISSUE TITLE
Cherokee glyph `uni13AE` too high

### ISSUE THREAD

**Issue by lemzwerg** [googlei18n/noto-fonts#713]
For my taste, glyph `uni13AE` is too high.  This glyph is taller than all other glyphs in the font, and I wonder why.  IMHO, there is no reason for this.  Other Cherokee fonts like Adobe's 'Phoreus' font don't have this either, and I suggest to follow.

**Comment by marekjez86** [comment]
@lemzwerg : you are right (I picked some random characters and compared PlantagenetCherokee by Tiro Typeworks which is on my Mac with NotoSansCherokee). Here's the jpg:

![cherokee](https://cloud.githubusercontent.com/assets/13322623/16065004/57748a84-325b-11e6-9dd5-d56925b15710.jpg)

While I agree with you about the height, I do not think I want to do anything to the existing unicase font. Why?
1. we are "building" a dual case font which will coexist with the unicase font but I hope will take over.
2. I will pass this note to the designers of the dualcase cherokee font so they will take it into consideration when designing the font.
3. since the existing unicase font was designed under guidance of Cherokee Nation and reviewed by them, I would hesitate to change it if there's some historical reason for the height of uni13AE

Hence this resolution: 1. past font - no change 2. future font (unless there's a historical reason for it) - will adhere to the spirit of your note [but I need to ask you to review the design early - meaning soon; could you do it?].

Is this OK?

**Comment by lemzwerg** [comment]
Well, I've looked up the `official', historical Cherokee font, and `uni13AE` does *not* have an extended height.  Maybe the Cherokee people have missed this.

Given that I'm not a font designer, I can't really review the design, but I'm certainly able to have a look :-)
