### ISSUE TITLE
hinted: Does not have Syriac fonts

### ISSUE THREAD

**Issue by LionNatsu** [googlei18n/noto-fonts#724]
Syriac fonts:

```
NotoSansSyriacEastern-Regular.ttf
NotoSansSyriacEstrangela-Regular.ttf
NotoSansSyriacWestern-Regular.ttf
```

Are missing from the `hinted` directory, while they are found in `unhinted`. More fonts might be missing from the `hinted` directory, I am yet to make sure of that.

**Comment by jungshik** [comment]
As you found out, not all fonts are hinted.

**Comment by marekjez86** [comment]
Hinting is a separate process which required additional effort/payments. Not all fonts were hinted and not all fonts will be hinted in the future. Need for Syriac hinted noted.

**Comment by davelab6** [comment]
Sadly Syriac is not in https://github.com/lemzwerg/noto-hinted 

cc @lemzwerg

**Comment by lemzwerg** [comment]
Well, ttfautohint doesn't support Syriac yet.  Something for the future...

**Comment by brawer** [comment]
@lemzwerg, could you document how to support a new script? Then, if somebody wants hinting for Syriac (or Ol Chiki, or whatever else), they can add it themselves and send you a pull request.

**Comment by lemzwerg** [comment]
Adding a new script is demonstrated for example with the following commit in ttfautohint (this adds Ethiopian):

http://repo.or.cz/ttfautohint.git/commitdiff/d14c7c0758539921b58f2854777175fde1267fb1

The corresponding entry in the 'noto-hinted' is

https://github.com/lemzwerg/noto-hinted/commit/cb76bff511932b903bf7bae23ad4c54d168878d4

You then have to do the following steps.

1. Say `make html` to run ttfautohint on the fonts (which must be present in the `unhinted` directory of the `noto-fonts` git repository) and to generate the HTML webpages.

2. Commit the changes to the repository.

3. Say `make` to run the screenshooter program which takes screen snapshots from BrowserStack.  This can easily fail so it might be necessary to repeat `make` until all screen shots are taken.

Note that currently the 'noto-hinted' repository is out of sync with the fonts in 'noto-fonts', due to lack of time and progress with a new ttfautohint release :-/

**Comment by brawer** [comment]
Awesome; can you add that to the ttfautohint docs/site/repo? Thank you 💛

**Comment by lemzwerg** [comment]
I've now added the stuff related to ttfautohint to the documentation and to the description of the noto-hinted repository.
