### ISSUE TITLE
Sylheti Nagari conjuct characters issue

### ISSUE THREAD

**Issue by Sagir8453** [googlei18n/noto-fonts#743]
Hi, Sylheti Nagari conjuct characters are not supported, please do something for it.

**Comment by KatMomoi** [comment]
I wonder if there is a clearly defined set of rules for conjuncts and they are specified in the Unicode standard. Can the bug filer add some additional info?
Roozbeh -- has any discussion on Syloti Nagri come up in recent Unicode technical committee discussions?

**Comment by KatMomoi** [comment]
Cf. http://www.unicode.org/versions/Unicode9.0.0/ch15.pdf

Not sure if the description here is sufficient to implement conjuncts in a font. Added behdad also to discussion.

**Comment by jungshik** [comment]
From the Unicode standard chapter 15, 
>  Conjuncts are not limited to sequences involving dead consonants
> but can be formed from pairs of characters of almost any type (consonant, independent
> vowel, dependent vowel) and can represent a wide variety of syllables. 

Wow...  

@Sagir8453, what kind of conjuncts do you expect to see?  Do you have any specific conjuncts in mind?

**Comment by roozbehp** [comment]
This is what I found on conjunct usage (just search for "conjunct"): http://www.unicode.org/L2/L2002/02388-syloti-proposal.pdf

**Comment by TidharC** [comment]
Section II.2 of the proposal above lists some common conjuncts.  We may need a more comprehensive conjunct collection, if it exists.

**Comment by roozbehp** [comment]
You can also look at the list of conjuncts supported by other Syloti Nagri fonts: http://scriptsource.org/cms/scripts/page.php?item_id=script_detail_font&key=Sylo

**Comment by jungshik** [comment]
Which encoding model was accepted of the two models in the proposal referred to in @roozbehp's comment? It looks like the viramic model (iii 3.1) was taken instead of the alternate model ( iii 3.2 of the proposal) according to my reading of TUS chapter 15.

**Comment by roozbehp** [comment]
> Which encoding model was accepted of the two models in the proposal referred to in @roozbehp's comment? It looks like the viramic model (iii 3.1) was taken instead of the alternate model ( iii 3.2 of the proposal) according to my reading of TUS chapter 15.

No idea. I wasn't involved with the Indic scripts then. You need to dig into the meeting notes and make your conclusions based on what's in the Core Spec.

**Comment by sridatta1** [comment]
These are the resources which I could get
http://www.sylheti.org.uk/fonts/
http://www.sylhet-nagri.com/Online_Read.php
http://eap.bl.uk/database/results.a4d?projID=EAP071
It seems from generic Virama model was accepted from my reading of  TUS chapter 15.
L2/02-388 had proposed C1+ZWJ+C2 to form consonant conjuncts. But this sequence is unknown in Indic and uses ZWJ identically to virama. This isn't reasonable and uses ZWJ in totally new way and is problematic.
http://www.unicode.org/L2/L2005/05130-syloti-enc-model.pdf discusses encoding model for Syloti Nagri
Here we may note that Unicode encodes written forms and not the sounds thereof regardless of their phonological value.

**Model of rare non- consonant consonant conjuncts**
(Here representing Syloti Nagri using Devanagari)

1.  False conjuncts
मत written as म्त
मान as म्ना
बीबीर as बीब्री
since written forms are encoded  regardless of the reading of the text. These should be represented as MA+HASANTA+TA, MA+HASANTA+NA+VS AA,etc.
(see textual representation and reading of ററ in Malayalam).

2. Other vowel letter and a following consonant, spacing vowel sign and a following consonant etc 
These may be handled at font level using substitution through font features since they are rare and some are founds of lines in manuscripts due to paucity of space. Using Virama or Joiner might complicate the model.
But current Indic Syllabic Category of SYLOTI NAGRI SIGN HASANTA is Pure_Killer which needs to be changed to Virama.

**Comment by kmansourMT** [comment]
The current version of the font supports a group of two-consonant ligatures that can be trigged through the use of the OpenType dlig feature (discretionary ligature). Since not all computing environments readily give access to this feature, I propose that we provide a parallel mechanism to trigger the formation of this set of ligatures through the use of the ZWJ.

**Comment by marekjez86** [comment]
[NotoSansSylotiNagri-Regular.otf.zip](https://github.com/googlei18n/noto-fonts/files/1516334/NotoSansSylotiNagri-Regular.otf.zip)

@Sagir8453 , @sridatta1 : could you verify that the above font fixes the issue?

**Comment by kmansourMT** [comment]
The attached PDF shows all the 18 discretionary ligatures included in the font. 

[NotoSylh-ligs.pdf](https://github.com/googlei18n/noto-fonts/files/1519079/NotoSylh-ligs.pdf)

**Comment by marekjez86** [comment]
@kmansourMT : thank you. closing the issue

**Comment by Sagir8453** [comment]
@marekjez86 hi, the conjuncts still don't work on Android. I used Picsart to check the font you provided, but it doesn't show the conjuncts.

**Comment by lianghai** [comment]
@Sagir8453 To ligate the letters, the font currently relies on the `dlig` feature, which is not on by default and needs to be switched on manually. To have an encoding level's solution, the Unicode Standard needs to have a decision.
