### ISSUE TITLE
UI versions not included in download zip

### ISSUE THREAD

**Issue by pnorman** [googlei18n/noto-fonts#744]
https://noto-website.storage.googleapis.com/pkgs/Noto-hinted.zip does not contain any of the UI versions of the fonts, e.g. no NotoSansUI-Regular.ttf or NotoSansMyanmarUI-Regular.ttf

**Comment by marekjez86** [comment]
Paul, currently UI fonts are "work-in-progress". Once we release them they'll appear on the official Noto site. However, I'd recommend trying https://github.com/googlei18n/noto-fonts/tree/master/alpha/from-pipeline if you really want the UI fonts now.

**Comment by pnorman** [comment]
> Paul, currently UI fonts are "work-in-progress". Once we release them they'll appear on the official Noto site. However, I'd recommend trying https://github.com/googlei18n/noto-fonts/tree/master/alpha/from-pipeline if you really want the UI fonts now.

The UI fonts are in the `hinted` and `unhinted` directories - does this not indicate they are released? If not, where is released status indicated?

**Comment by marekjez86** [comment]
alpha directory means experimental
hinted/unhinted directories contain tested and release ready fonts which might be or might not be yet pushed to noto font web site yet -- it takes time to update the official noto font web site.

feel free to grab what you want from the  hinted and unhinted directories  here

**Comment by dougfelt** [comment]
Originally we didn't include the UI fonts in the download bundles because we were concerned people would find it confusing.  We've found however that people are also confused if they are not.  We will update the get/noto site with new bundles that include these, I expect sometime next week.  For now you can get them from this repo under the hinted and unhinted directories, they are as well-tested as other fonts in those directories.

**Comment by marekjez86** [comment]
reopened and left it assigned to @dougfelt since he wrote "We will update the get/noto site with new bundles that include these, I expect sometime next week." -- we'll close it then.

**Comment by verdy-p** [comment]
@marekjez86: 29 days ago, you wrote "next week". The download zip still don't have any UI fonts.

**Comment by dougfelt** [comment]
@verdy-p which download zip(s) are you not finding the UI fonts in?  I get them in the Noto Sans (LGC) download, and also in the zip I get when I click 'Download All Fonts'.  I'm using Linux and these are the 'hinted' zips.

**Comment by dougfelt** [comment]
@verdy-p ping?

**Comment by verdy-p** [comment]
They are not all there in the zip, there are more Ui fonts on the project page for some scripts. But may be they are still not at the "release" status. yes "Nata Sans" has an Ui version, but here we're speaking about other scripts, notably those that normally need higher line heights (but that should be reduced for the UI version to match the same UI line-height across alls scripts, e.g. for use in an interlanguage navigation bar showing many translated titles, or in a language selector box showing native language names with a coherent line-height for entries, or in tabular data showing translations side by side without increasing too much the total row height, or shwoing translations in vertical lists while keeping all rows wit hthe same height, the alternative being to use a static line-height=1.6 for all rows).

**Comment by dougfelt** [comment]
@verdy-p Thanks.  We understand the use cases for UI fonts, we do provide them for some scripts after all...

>  there are more Ui fonts on the project page for some scripts

I'm not sure what 'project page' you are referring to.

Are you saying that there are Noto UI fonts that **already exist in hinted/unhinted** that are not in the download zips? Or are you saying that there are scripts for which Noto should provide a UI version but don't?  In either case, it would help if you listed the scripts you're referring to.

**Comment by verdy-p** [comment]
Basically these are the UI font for scripts that need higher line-heights in normal non-UI text, notably scripts of South-East Asia, as well as the Nasthalik variants of Arabic (for Persian, Urdu...) .

The UI version of Latin/Greek/Cyrillic also is normally using slighly smaller capitals (to allow for diacritics above them, without truncating them, such as "Î" used in French, or "Ñ", or in Vietnamese using two diacritics), than in normal non-UI text (which require at least 1.5em for these diacritics, instead of 1.4em for the UI version). What this means is that the "M" letter, and all basic Latin capitals in UI version should be in fact slightly smaller than 1em, even if the "em-height" is still 1em.

However I don't know what was your design decision about the line-height suggested for all scripts in UI: 1.4em or 1.5em? For now MEdiaWiki still uses 1.6em for showing all scripts with the same line-height (independantly of the fact we could have "UI" font versions for these scripts, showing more compact text.

You could also do the opposite: set all UI fonts to use 1.6em line-height for all scripts, so that Basic Latin capital letters like "M" would still be 1em high, without reducing their glyph with "tall" diacritics placed above them (such as accents, circumflex, tilde, or stacked accents in Vietnamese and African languages). This would have the effect to force a UI to use taller lines, and less compact text (buit this will remain a problem for rendering on small screens that would really like to compact these lines to show more items vertically on screen, e.g. in side menus, and without forcing viewers to scroll vertically).

So this decision for the unified value of the "UI line-height" is still debatable.

**Comment by dougfelt** [comment]
@verdy-p 

So, this is all useful information.  But... I asked some specific questions, and have yet to receive a direct answer.  We are not, in this bug, opening up a discussion about UI line height(s), or what that/those line height(s) should be.  Please file another bug for that if you want.

This bug is specifically and only about whether the UI fonts in this repo are available in the download zips available from the user-facing site at https://www.google.com/get/noto/.  I maintain that they are.  Please provide an example of ones that are not if you don't want me to close this bug.

**Comment by pnorman** [comment]
Both the macOS and Windows releases have 32 files matching `*UI*`, which is the same as the `release/hinted`, `release/unhinted`, `hinted`, and `unhinted` directories in the repo.

**Comment by IceflowRE** [comment]
Sorry for the necro bump, but got they removed again? or are they replaced with the "Display" version? at least the `NotoSansUI-Regular.ttf` iam missing, not the language specific.

**Comment by barmadrid** [comment]
Same question as @IceflowRE 

Trying to set a generic "system-ui" fontconfig family name and was wondering if Noto Sans Display is more appropriate than Noto Sans, since we no longer have the UI version! 

@davelab6 your insight on this is appreciated.

**Comment by marekjez86** [comment]
Noto Sans is the UI version (without UI suffix -- I have no idea why this inconsistency in naming). It is also intended for the body paragraphs of the text. Noto Sans Display (and any Noto * Display in LatinGreekCyrillic fonts are intended for headings and titles, etc).
