### ISSUE TITLE
Kannada Noto Sans and Serif Issue

### ISSUE THREAD

**Issue by MayuraVerma** [googlei18n/noto-fonts#760]
The below text in "Pages" in Mac OS Sierra, renders text differently for Kannada Noto Sans and Serif.

With Noto Sans, glyphs are not substituted correctly.
With Noto Serif, glyphs are not positioned correctly.

Please review. 

Text is taken from the below link.

https://kn.wikipedia.org/wiki/ಆಂಗ್ಲ

kannada noto sans
![kannada noto sans](https://cloud.githubusercontent.com/assets/14062593/19224898/b11d4044-8e54-11e6-8b6d-9361141c4189.png)
kannada noto serif
![kannada noto serif1](https://cloud.githubusercontent.com/assets/14062593/19224897/b11d27f8-8e54-11e6-83ea-6ca58d24c638.png)
kannada noto serif (bigger font size to show the glyph discontinuity.
![kannada noto serif2](https://cloud.githubusercontent.com/assets/14062593/19224899/b126e2a2-8e54-11e6-8e69-36d52befb682.png)

Text:
ಇಂಗ್ಲೆಂಡಿನ ಜನರ ನುಡಿ. ಕಾಮನ್ವೆಲ್ತ್ ಮತ್ತು ಅಮೆರಿಕ ಸಂಯುಕ್ತ ಸಂಸ್ಥಾನಗಳಲ್ಲಿ ಇದನ್ನು ಮಾತೃಭಾಷೆಯನ್ನಾಗುಳ್ಳ ಜನರ ಸಂಖ್ಯೆ 25 ದಶಲಕ್ಷ. ಆಫ್ರಿಕ, ಭಾರತ ಮತ್ತು ಜಪಾನುಗಳಂಥ ಇತರ ದೇಶಗಳಲ್ಲಿ ಎರಡನೆಯ ಭಾಷೆಯಾಗಿ ಇಂಗ್ಲಿಷನ್ನು ಬಳಸುವವರ ಸಂಖ್ಯೆಯೂ ಅಷ್ಟೇಇದೆ. ಈ ದೃಷ್ಟಿಯಿಂದ ಚೀನಿ ಭಾಷೆಗೆ ಪ್ರಥಮ ಸ್ಥಾನವಾದರೆ ಇಂಗ್ಲಿಷಿಗೆ ದ್ವಿತೀಯ ಸ್ಥಾನ (500 ದಶಲಕ್ಷ). 873 ಮಿಲಿಯನ್ ಇಂಡೊ-ಯುರೋಪಿಯನ್ ವರ್ಗಕ್ಕೆ ಸೇರಿದ ಭಾಷೆಗಳಲ್ಲಿ ಒಂದು. ಇದನ್ನು ಮೊದಲ ಭಾಷೆಯಾಗಿ 309-400 ಮಿಲಿಯನ್ ಜನ ಮಾತನಾಡುತ್ತಾರೆ, ದ್ವಿತೀಯ ಭಾಷೆಯಾಗಿ 199 ಮಿಲಿಯನ್ - 1.4 ಬಿಲಿಯನ್ ಜನ ಮಾತನಾಡುತ್ತಾರೆ. ಒಟ್ಟಾರೆ 500 ಮಿಲಿಯನ್ನಿಂದ 1.8 ಬಿಲಿಯನ್. ಇದು 53 ದೇಶಗಳಲ್ಲಿ ಅಧಿಕೃತ ಭಾಷೆಯಾಗಿದೆ.

**Comment by jungshik** [comment]
Might or might not be an issue specific to Mac OS(coretex). 
@brawer @marekjez86

**Comment by jungshik** [comment]
@MayuraVerma , thanks a lot for the report. Could you list problematic sequences for Noto Sans and Noto Serif below?  I'm sorry, but it's rather hard for me to find them in a long paragraph (you included in the report).   

BTW, how are those sequences rendered by either Chrome or Firefox on Mac?  Are they better or worse?

**Comment by MayuraVerma** [comment]
This issue is "Pages" in Mac OS Sierra

With Noto Sans KANNADA: 
Glyphs are not substituted correctly. They are highlighted in "RED" color above. I will list them below for your reference.
ಸ್ಥಾ
ನ್ನಾ
ತ್ತಾ
ಟ್ಟಾ
With Chrome or Firefox on Mac, this is not an issue.

With Noto Serif KANNADA:
Glyphs are not positioned correctly. In the OP, this combination is highlighted in bigger font size to show the glyph discontinuity. 
ನ್ನಾ
With Chrome or Firefox on Mac, this is not an issue. But there is multiple issues with Noto Serif Kannada with Chrome on Mac, reported in issue #759

**Comment by brawer** [comment]
After installing NotoSansKannada-Regular.ttf with FontBook, I entered the string ಸ್ಥಾ ನ್ನಾ ತ್ತಾ ಟ್ಟಾ into an empty Pages document, then selected it. Then, I pressed ⌘T to get the font selection dialog, and picked “Noto Sans Kannada”. Here’s how it looks — is this wrong?

<img width="894" alt="screen shot 2016-10-11 at 3 22 46 pm" src="https://cloud.githubusercontent.com/assets/1527880/19271852/ac404878-8fc6-11e6-9871-0dab24078901.png">

I also ran the string ಸ್ಥಾ ನ್ನಾ ತ್ತಾ ಟ್ಟಾ through both HarfBuzz and CoreText, and both engines were producing the exact same output.

Admittely, it’s pretty hard to select Noto Sans Kannada in Pages. By default, Pages seems to hide (from the popup menu in the right-hand panel inside the document window, not from the font picker that shows up when pressing ⌘T) any fonts that don’t have Latin coverage. We could fix this by shipping a much larger pan-Unicode font instead of the current shards. If this large font included Latin, Pages would probably not suppress it anymore from the popup menu. However, this would have other downsides (very large file size, and we’d have to find a solution for language-specific line metrics). Adding @xiangyexiao because it sounds like a product/usability problem caused by our current micro-sharding.

**Comment by brawer** [comment]
Likewise, the string ನ್ನಾ  seems to be rendered correctly (without a visible discontinuity) by Pages when choosing Noto Serif Kannada. Again it’s not easy to select the correct font, for the reason described above.

<img width="839" alt="screen shot of Noto Serif Kannada in Pages" src="https://cloud.githubusercontent.com/assets/1527880/19272528/3acc2272-8fc9-11e6-8337-c2a976b38c87.png">

**Comment by MayuraVerma** [comment]
@brawer I noticed the same issue initially. I was not able to find the Noto Serif Kannada in the font list. I ran multiple checks to see if font was installed correctly. I created a Word document with Noto Serif Kannada and opened it in Pages to see if the font shows up in the list.
I thought it was Pages issue. If you can do something in the not collection, to make it visible. Please do the needful.

Regarding the original problem "ನ್ನಾ"discontinuity. I am using mac OS Sierra. If that makes a difference. Also, I copy the text from wiki article and pasted in the pages.

**Comment by brawer** [comment]
Indeed, CoreText as of macOS 10.12 Sierra seems to have a regression. I’ve added test case [SHKNDA-2](https://raw.githack.com/icu-project/text-rendering-tests/master/reports/CoreText.html#SHKNDA-2) to the [text rendering test suite](https://github.com/icu-project/text-rendering-tests) and will work with Apple to resolve it. Thanks again for telling!

![screen shot 2016-10-11 at 18 03 14](https://cloud.githubusercontent.com/assets/1527880/19278366/3182bfb4-8fdd-11e6-8a49-d7ee8226de2f.png)

**Comment by JelleBosmaMT** [comment]
The observed defect is what you would expect to see if the shaper is not re-ordering the vowel sign AA in front of the subscript consonants, as it is supposed to do. Therefore this is a shaper bug indeed, not a font issue. As I have been using Mac OS and Pages for design proposals and proofing for the new versions of Noto Sans Kannada, it is safe to say this has been fixed and this issue #760 can be closed.

**Comment by MayuraVerma** [comment]
Yes. this can be closed.
