### ISSUE TITLE
Noto Sans Myanmar issues on iPad

### ISSUE THREAD

**Issue by SamaneriVimala** [googlei18n/noto-fonts#769]
The rendering of the Noto Sans Myanmar font is flawed on iPad.
The full discussion on this topic and testing on different Apple systems is here:
https://discourse.suttacentral.net/t/help-needed-from-apple-users/3306

To summarize: on iOS10 the issues seem to be solved except for in the Safari and Firefox Reader View, where the diacritics can still appear separate from the character they belong to.
On older systems, diacritics seem to move to the next character or appear different from what they are supposed to be, on all browsers and in all view types.

**Comment by brawer** [comment]
Just clarifying: The Noto Sans Myanmar font is correct, but Apple’s iPad does not render it correctly? If that’s the case, can you give me ~5 Myanmar words that show the problem? If you do this, I’ll add test cases to a common [test suite for text rendering](https://github.com/icu-project/text-rendering-tests) that we’re developing at Unicode.

**Comment by SamaneriVimala** [comment]
That's indeed the case.

I have made a few screenshots of the problems.

In iOS10 in Safari and Firefox Reader there are is only one mistake left that I can find:
အကျွန်ုပ်သည်
သွားလတံ္တနည်း

in iOS9 and older in all browsers there are many problems:
သဗ္ဗာသဝသုတ်
အကျွန်ုပ်သည်
သာဝတ္ထိ
ဤသို့
မြတ်စွာဘုရားသည်
သွားလတံ္တနည်း

If you need any screenshots of the problems, please let me know.

While doing this, I also found that the following word renders wrongly on my Ubuntu 16.04 machine on Chrome and Firefox (normal view + reader):
သွားလတံ္တနည်း

**Comment by jungshik** [comment]
သွားလတံ္တနည်း

I guess the above is problematic, right?  @SamaneriVimala

**Comment by SamaneriVimala** [comment]
Exactly. That's right.

**Comment by hrhatada** [comment]
Seems https://suttacentral.net/my/mn2 page’s web font is not loaded on OSX with browser’s default font setting.  I tested on Chrome, FF & Safari on OS X 10.11.6. 

When I opened the page with the default setting with Chrome & FF (Times New Roman & Arial), I saw the same problem as SamaneriVimala mentioned, however after I changed Chrome & FF’s web font to Noto Sans, the problem was disappeared.  Once the browser successfully loaded the font either local or remotely(web font), the page seems displayed correctly.

In addition, iOS & Safari does not let an user to change the default web font(there is a way, but not easy), so the problem stays.

I tested this with Chrome on Win7 & Ubuntu, and didn’t see the problem.  

![image](https://cloud.githubusercontent.com/assets/16353449/19493794/0445ccea-9531-11e6-9241-fc10889560c0.png)

**Comment by hrhatada** [comment]
However, something is wrong with Noto Sans Myanmar on OS X (and iOS).  I observed the font rendering problem on other OS X apps: TextEdit & LibreOffice.  I copied & pasted a text block from https://suttacentral.net/my/mn2, and applied Myanmar NM & Noto Sans Myanmar for each block.  The text used Noto Sans Myanmar had rendering problem as below.

Again, this text edit app’s rendering problem didn’t happen on Window’s app (I used WordPad)

![image](https://cloud.githubusercontent.com/assets/16353449/19494376/ac83441c-9533-11e6-85a6-028b182be9f7.png)

**Comment by SamaneriVimala** [comment]
I use Ubuntu 16.04 and that only gives a problem in the following line which does not go away with changing the Chrome web font to Noto Sans:
https://suttacentral.net/my/mn2/27

**Comment by JackfromMc** [comment]
It is because it is wrongly written, it is not a rendering issue
They wrote တ ံ ္ တ     တံ္တ
instead of တ ္ တ ံ     တ္တံ

**Comment by brawer** [comment]
See the [Unicode FAQ for Myanmar](http://www.unicode.org/faq/myanmar.html). It’s not Noto’s problem if a broken web page fails to use Unicode.
