### ISSUE TITLE
Kannada text issue 3

### ISSUE THREAD

**Issue by MayuraVerma** [googlei18n/noto-fonts#793]
ಡೋಂಗಿ has issues rendering text in mac OS. Please review.

![screen shot 2016-11-17 at 8 09 07 am](https://cloud.githubusercontent.com/assets/14062593/20392379/33bca894-ac9d-11e6-8cfe-52578702a32d.png)

**Comment by MayuraVerma** [comment]
@brawer please review this.

**Comment by TidharC** [comment]
It seems the problem is with the glyphs in letter OO (U+0CCB or U+0CCA U+0CD5) being swapped when the letter is postfixed by an Anuswara (U+0C82).
For comparison, this happens with Noto Sans Kannada and not with Kannada MN.

Repro with TextEdit on Mac OS 10.12

![notosanskannada](https://cloud.githubusercontent.com/assets/16353803/20404137/71106b3e-acb8-11e6-8b20-ab93c7b9a0e2.png)

**Comment by MayuraVerma** [comment]
@TidharC Thank you, is this a font issue? 
if so, same problem is present in Tunga. Is there a way to report it to Microsoft?

**Comment by TidharC** [comment]
I don't think it's a font issue.  I tried the same char sequence on different platforms; it's displayed correctly in:
HarfBuzzViewer (Linux)
BabelPad (Windows 8.1)
Chrome, Firefox, Safari (MacOS 10.12).

So far I see the glyph transposition only in TextEdit on MacOS.

@brawer, do you think this is an Apple bug?

**Comment by brawer** [comment]
@TidharC, mind adding a test case to https://github.com/unicode-org/text-rendering-tests? That will tell if it’s a CoreText bug, in a form that is easy to reproduce for anyone (including Apple).

**Comment by MayuraVerma** [comment]
ಜಾ಼ ಕಿರ್ 
ಜಾ಼ಕಿರ್
I am not sure if this is harbuzz issue or noto sans/serif issue.

**Comment by MayuraVerma** [comment]
This is resolved in mac of High sierra.
