### ISSUE TITLE
Capital i has serif in noto sans

### ISSUE THREAD

**Issue by vegarda** [googlei18n/noto-fonts#818]
Isn't it Noto "SANS"?

**Comment by khaledhosny** [comment]
That is not an unusual thing to do, I guess it helps differentiate I for l.

**Comment by twardoch** [comment]
Uppercase I, lowercase l and sometimes 1 tend to be similar and designers like to differentiate it to aid readability in words like "Illumination"

**Comment by paul4ig** [comment]
The mindset of the OP is the main problem I have with font designers. Too many of them are concerned with style/art/form/fashion and not enough concerned with the fact that the primary purpose of a font is for COMMUNICATION. Who says that "sans" fonts have to look a certain way other than fashionistas? If Google truly wants to innovate and improve global communication you should implement #821 and make I and l completely unambiguous by keeping the bars on the I and also adding a tail to the l.

**Comment by twardoch** [comment]
I can echo the concerns by @paul4ig is so far that the lowercase l without the tail can be differentiated from an uppercase I that has top and bottom serifs but only if your already know that the uppercase I had the top and bottom serifs. :) In other words, when the reader is unfamiliar with the font, this still doesn't help. In words such as "Illinois" both I and l appear, so it's obvious which is which. But especially in nonsensical phrases like wifi passwords e.g. "aR65Hus0lfG3", you really don't know what the letter after the 0 is because you don't see the opposition between l and I there.
