### ISSUE TITLE
Google chrome + Telugu Language bug.

### ISSUE THREAD

**Issue by ramasuresh** [googlei18n/noto-fonts#826]
I have installed the Google Input Tools on Windows. It was working fine one month back. But now I am having issue while typing the Telugu language font. 
After second word, cursor is focusing out. So I can not type anything on that. Could please look into it. 
Note: I have noticed this behavior on facebook.com in chrome only. 
It is working fine in  facebook.com firefox. 

Weird behavior.

**Comment by fitojb** [comment]
This bug tracker is for the Noto fonts, and I don’t think that this issue belongs here at all.

**Comment by marekjez86** [comment]
@ramasuresh : are you in this case in any way using Noto Telugu font? or this is ONLY related to the use of Google Input Tools Chrome extension?

**Comment by hrhatada** [comment]
Assign back to the reporter.  Please let us know this is the font problem or not.  

You can install NotoSansTelugu-Regular.ttf font from https://github.com/googlei18n/noto-fonts/tree/master/hinted and copy & past some Telugu text block into a document file and apply the above Telugu font to the text block you pasted.

If you don't see any font issue, then the bug is in the IME

**Comment by jungshik** [comment]
@ramasuresh It looks like your issue had better be filed against Chrome. You can file a bug against Chrome at https://crbug.com 

Closing for now. Reopen it if you have this issue ONLY when you install Noto Sans Telugu and set Telugu font to Noto Sans Telugu in Chrome.
