### ISSUE TITLE
New Adlam fonts - the "joined" version doesn't show characters joining

### ISSUE THREAD

**Issue by sven-oly** [googlei18n/noto-fonts#828]
The new Adam fonts include an "unjoined" version NotoSansAdlam-Regular.ttf
and 
NotoSansAdlamUnjoined-Regular.ttf, which is supposed to join the characters at the baseline.

However, this test does not show any joining even when the Noto Sans Adlan font is selected.
http://adlamtesting.appspot.com/

To test, paste the following text and use the font selector at the bottom.
𞤢𞤣𞤤𞤥𞤦𞤧𞤨𞤩𞤪𞤫𞤬𞤭𞤮𞤯𞤰𞤱𞤲𞤳𞤴𞤵𞤶𞤷𞤸𞤹𞤺𞤻𞤼𞤽𞤾𞤿𞥀𞥁𞥂𞥃

**Comment by punchcutter** [comment]
The font does join, but not on that testing page. Since joining is optional in Adlam you need to turn on the joining features fina, medi and init, but even that doesn't seem to work correctly in browsers. If I put any variation of 
`font-feature-settings:"fina", "medi", "init";`
in the CSS it still only shows a mix of init and medi or something, but it doesn't apply all three correctly. Also with the latest harfbuzz I don't see correct joining behavior. I tried variations of

`hb-view NotoSansAdlam-Regular.ttf --features=init,medi,fina`

and I see the same half shaped text. Maybe @behdad knows what's going on there.

**Comment by punchcutter** [comment]
Here's what I get in hb-view with fina,medi,init specified and another screenshot of how it should be rendered when fina, medi and init are used.
![hb-view_adlam_joined](https://cloud.githubusercontent.com/assets/11257204/22348013/ef094870-e3be-11e6-9a86-95a9df7a2bd2.png)
![adlam_joined](https://cloud.githubusercontent.com/assets/11257204/22348012/ef069184-e3be-11e6-8373-162df0f0fd25.png)

**Comment by dougfelt** [comment]
Behdad will have to say how this gets processed by default.  fina/medi/init
would typically be applied by the layout engine for Arabic when the script
was detected, and not require any external input, so if that's the
expectation for Adlam then all OT layout engines would have to do it.
Perhaps this is in a later version of Harfbuzz than the browser was using?

**Comment by behdad** [comment]
Humm. HarfBuzz was NOT passing Adlam through Arabic shaper.  Fixing now.

**Comment by punchcutter** [comment]
Looks good in hb-view now
![adlam_joined_hbfixed](https://cloud.githubusercontent.com/assets/11257204/22353994/0a29a1a4-e3d8-11e6-87f9-53d350ccc184.png)

**Comment by sven-oly** [comment]
Great. Thanks for finding and fixing this.

Craig Cornelius

**Comment by KrasnayaPloshchad** [comment]
> I asked about Windows and Uniscribe will also be updated at some point to fix this.

You’d also asked about LibreOffice, since it also uses HarfBuzz everywhere.
