### ISSUE TITLE
Missing Characters in Arabic versions of Noto

### ISSUE THREAD

**Issue by droopup** [googlei18n/noto-fonts#829]
In reviewing the glyphs available for Noto Naskh Arabic and Noto Kufi Arabic, I find only a limited set of punctuation marks: exclamation point, period, comma. Numerals. No western letters, nor the rest of the extended character set, such as parenthesese, brackets, plus/minus, even semicolon! The following are all missing:

(a-z) (A-Z)    "';_    @#%^&*?°     (){}|<>/\[]  +=-±     ®©™     $¢£¥€

Tofu city.

These are all present in the CJK and other international fonts...so their absence here is mysterious. For the moment, this makes these fonts unusable for translation.

**Comment by brawer** [comment]
Make sure to also install the Noto Sans Latin/Greek/Cyrillic font on your system; that contains the punctuation glyphs you’re looking for. Admittedly this packaging is a bit painful for users, but we’d waste a lot of storage space if every script contained every symbol in Unicode. (When a glyph participates in kerning or glyph substitution, it still get duplicated).

**Comment by droopup** [comment]
Closed for Google, perhaps, not for me. And your reasoning is flawed: the CJK fonts contain many, MANY more characters than the Arabic fonts, yet the CJK fonts also contain the western characters. Translation is no problem in Chinese or Korean. 'fraid we'll just continue to use Microsoft Arial for Arabic. They didn't have any trouble including the Western Characters. Neither did Adobe. Or about a half-dozen other people doing Arabic fonts.  Not sure why it was a problem for Google. And "a bit painful" is an odd way of saying "useless".

**Comment by dougfelt** [comment]
Suit yourself.

**Comment by moyogo** [comment]
@droopup you can install https://github.com/fonttools/fonttools then use the pyftmerge tool to merge two fonts together. For example `pyftmerge NotoSansArabic-Regular.ttf NotoSans-Regular.ttf` will create merged.ttf from both fonts.

**Comment by droopup** [comment]
Moyogo: thanks, I'll give it a try.

Dougfelt: thanks for nothing. This your idea of "don't be evil?"

**Comment by mboeringa** [comment]
I would like to second @droopup requests for basic Latin, and especially punctuation like brackets, but would like to extend this request to **_all_** Noto Fonts.

This is not a joke, this is absolutely necessary for cartographic purposes in many applications and especially **desktop** GIS's like QGIS and ArcGIS, that cannot handle font fallback and other stuff so easily as web based applications.

Look at the attached image, where the first line of the dual language label is rendered using Noto Sans, and the second text line using Noto Sans Thai. In the image, the brackets that have been dynamically added to the second line that contains the Thai text, end up being tofu, because apparently, Noto Sans Thai doesn't contain the necessary glyphs for something as basic as a pair of brackets.

![noto_sans_thai_bracket_tofu](https://user-images.githubusercontent.com/7635726/27713444-0b594c14-5d2c-11e7-9483-08e9fcb66aa8.png)

This could be solved by giving each bracket its own formatting tags and reference Noto Sans like the first line, but this seems utterly overkill for such a simple thing - putting brackets around a place name in a native language - and complicates maintenance of styles, or the scripting of labeling using a scripting language like Python.

If just the basic Latin is included, at least any dual language English / Other language labels won't necessarily require a second font and additional formatting tags to deal with this issue. This would really simplify basic multilingual map making, with English as first or second language, which I think would cover by far the majority of multilingual map projects.

**Comment by dougfelt** [comment]
These fonts are not designed for your use case.  See Moyogo's comment if you want to create versions of these fonts with more Latin.

**Comment by droopup** [comment]
Doug Felt: are you just a troll, or does someone actually pay you to do this? The stated purpose of Noto is to be used in ALL cases in ALL languages. It is not meeting its stated purpose...apparently thanks to people like you. You make me understand why the EU decided to ding you guys to the tune of 2.7B. If you can put the western characters in the CKJ set, you can put them in anything. Installing and applying fonttools is NOT something every Tom, Dick and Harry can be expected to do. I've already opted for a different font. Google is blowing it big time on this.

**Comment by droopup** [comment]
Or...y'know...you COULD just come out and admit it:

"This is beyond Google's capabilities. We're not smart enough to do this."

Because I have to assume this is the case. Otherwise, you'd have just done it, since apparently all it requires is a few minutes with fonttools. Which couldn't possibly be beyond your capabilities.

**Comment by dougfelt** [comment]
I should know better than to reply to comments like this.  You should be embarrassed for your immaturity and sense of entitlement.

**Comment by droopup** [comment]
Yup, troll.

**Comment by mboeringa** [comment]
> I should know better than to reply to comments like this. You should be embarrassed for your immaturity and sense of entitlement.

I do think this is slightly unfair in relation to @droopup 's remarks, as I think his remarks are also the result of the **non existing** discussion about this subject and immediate closure of the thread he opened. I can sympathize with him in this respect.

Honestly, I think I have given at least a few good reasons why they need inclusion, and all we got in response as argument in favor of the current situation is "_Admittedly this packaging is a bit painful for users, but we’d waste a lot of storage space if every script contained every symbol in Unicode._" and "_These fonts are not designed for your use case._"...

Neither I nor @droopup suggested including "_**every symbol in Unicode**_", in fact, personally, I think I agree with the decision not to do so. But not including even basic Latin, really curtails the usability of Noto and its ability to show (trans)literated languages in basic multilingual applications, and in that respect I do think it would be fair if Google gave better and valid arguments as to why they think it should not be. Currently, I have seen none...

**Comment by droopup** [comment]
mboeringa: thanks for the support, but don't waste your breath. This guy's a troll. He doesn't speak for Google. I doubt he even knows that Unicode means.

Noto just ain't quite there yet. Clearly, Google is going to continue to develop it in its own sweet time. Make use of it where it's useful and find alternatives where it doesn't. See above suggestion from moyogo. Fonttools is not for the easiest framework to use, but with a bit of trial and error you can build viable font sets. They will, unfortunately, be unique to you, rather than generally applicable, but it IS a way to get over the wall.

**Comment by dougfelt** [comment]
@mboeringa, thank you for making a reasoned and non-inflammatory contribution to this thread.

The decisions about Noto packaging were made many years ago.  This includes whether to package multiple scripts in one font as well as how much to duplicate Latin and symbols across fonts.  The main impetus came from Android, which (especially at the time) was particularly space conscious.  Also our font development process involved working with multiple vendors, and providing Latin and Symbols across multiple fonts risked additional inconsistency in appearance and behavior.  It is difficult enough to manage tens of thousands of glyphs across 100 fonts.  Since our primary target platforms (Android, ChromeOS, Web) provide fallback in their rendering environments, we chose to rely heavily on fallback and minimize overlap in the fonts.  This allows us to somewhat reduce the engineering and management effort in building Noto.

Most recent engineering effort has gone towards building out the open source font pipeline, supporting variation fonts, and updating Noto to more recent versions of Unicode.  The open source pipeline builds fonts from Glyphs and/or UFO sources.  Having the source will make it easier to accept fixes from third parties or make quick patches if a designer isn't available via our vendors.  Variation fonts allow us to support more weights/styles with a smaller increase in footprint; again mobile is a driver for this as space is limited.  The next version of Noto (rolling out incrementally) will provide sources for the fonts and be built by the pipeline, and it will also support more recent versions of Unicode.  Currently Noto is mostly at Unicode 6 and 7 w.r.t. script and glyph coverage.  There are also many, many limitations in our support for different languages that use the same script; this is a challenge for us as often it's difficult to find the required expertise-- the open source pipeline should help there as well.

In this context, putting additional resources towards defining, building, and maintaining more or different packaging variants of the Noto fonts is low priority for us.  Priorities change and resources ebb and flow, currently we are not as well-resourced, and so not as ambitious, as we were a year ago.  This may yet again change, of course, but that's where we are now.  Hence our unsatisfying reply to your request.

**Comment by droopup** [comment]
There ya go. Now you know what it takes to get a straight answer out of Google. Thanks for your honesty.

**Comment by mboeringa** [comment]
Thanks @dougfelt for the in-depth answer. This is something I hoped for and at least explains the current situation well, even though it may not be satisfactory for me or @droopup and our applications. However, your anwser will hopefully also be a possible resource/reference for other people running into the same issues though.

I understand the difficulties and challenges you must be facing. Actually, it is only in the last 1-2 years or so, that I have progressively read up a bit on the subject about fonts, languages, glyphs, scripts and such, but that has indeed shown it to be a seriously tough subject, with many issues and pitfalls.
