### ISSUE TITLE
name variable fonts as -VF, instead of -GX

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/noto-fonts#830]
https://github.com/googlei18n/noto-fonts/tree/master/alpha/from-pipeline/unhinted/variable

GX refers to the old Apple format, not the new variable font format.

**Comment by twardoch** [comment]
I agree. While the suffixes are in no way standardized or mandatory, the "VF" suffix seems to be gaining popularity for variable OpenType fonts, and I think it should be used.

**Comment by marekjez86** [comment]
@ zjusbo : this ought to belong to you :-)

**Comment by zjusbo** [comment]
Resolved.

**Comment by davelab6** [comment]
Thoughts on `.ttv` and `.otv` as file extensions?

**Comment by twardoch** [comment]
@davelab6 And `.wofv`?

**Comment by dougfelt** [comment]
Doesn't the spec have recommendations on file name extensions for variable
fonts?

**Comment by Kanjilearner817** [comment]
You missed one. Noto Serif Thai, in variable-ttf.

**Comment by twardoch** [comment]
In the working group for variable fonts last year, we talked about new filename extensions. TrueType GX fonts were designed to be backwards-compatible, and since variable OpenType fonts are based on TrueType GX, they should inherit the principle of backwards compatibility wherever possible. 

In the last few years, OpenType added a lot of new glyph storage flavors (`SVG `, `CBDT`, `sbix`, `gvar`, `CFF2`), and everyone in the working was against new filename extensions. Why should we add any for `glyf+gvar` variable fonts, or for `CFF2` variable fonts? We didn’t add any for bitmap-only `CBDT` or `sbix` fonts, or for `SVG `-only fonts. And if we ever decided to add variability to `SVG `-based outline fonts, should we then add a new extension? And what if a font has a variable table `CFF2` plus a non-variable `SVG ` or `CBDT` table? 

TrueType and TrueType-based OpenType fonts had historically the `.ttf` extension. OpenType introduced the `.otf` filename extension for all fonts. Collections have the `.ttc` or `.otc` extension. 

Since in OpenType, the `.ttf` extension was thought as being optional, given a font vendor’s [“desire for compatibility on systems without native OpenType support”](https://www.microsoft.com/typography/otspec/otff.htm), but in fact, any OpenType font file regardless of the glyph storage format may use the `.otf` extension, I personally am in favor of using the `.otf` extension for **all** variable fonts, whether `glyf+gvar` or `CFF2`. 

Sure, a `glyf+gvar` font with `GSUB+GPOS` is, in a very limited way, backwards-compatible with systems that did not support OpenType, but all OSes since Windows 2000 support TrueType-flavored OpenType fonts with an `.otf` extension. Early `.ttf` OpenType fonts included the `kern` table in addition to `GPOS` kerning, and that was a sensible sign of backwards compatibility. But I think any reasonable support for variable fonts also presumes support for OpenType Layout. Therefore, I think it would be a good idea to give the `.otf` extension to `glyf+gvar` fonts, to underline that they’re **not** “old-style TrueType” but actually much more.

**Comment by twardoch** [comment]
Ps. the [spec](https://www.microsoft.com/typography/otspec/otff.htm) says: 

> Filenames

> OpenType fonts may have the extension .OTF or .TTF, depending on the kind of outlines in the font and the creator's desire for compatibility on systems without native OpenType support.

> In all cases, fonts with only CFF data (no TrueType outlines) always have an .OTF extension.

> Fonts containing TrueType outlines may have either .OTF or .TTF, depending on the desire for backward compatibility on older systems or with previous versions of the font.

> Collection fonts that use TrueType outlines should have a .TTC extension, regarless of whether layout tables are present or not. Collection fonts that use CFF or CFF2 outlines should have an .OTC extension.

It also notes on font collections: 

> An OpenType Font Collection (formerly known as TrueType Collection) is a means of delivering multiple OpenType fonts in a single file structure. The format for font collections allows font tables that are identical between two or more fonts to be shared. Font collections containing outline glyph data (TrueType, CFF, CFF2 or SVG) are most useful when the fonts to be delivered together share many glyphs in common. 

> Note: Even though the original definition of a Font Collection (as part of the TrueType specification) was intended to be used with fonts containing TrueType outlines, and this constraint was maintained in earlier OpenType versions, this is no longer a constraint in OpenType. Font collection files may contain various types of outlines (or a mix of them), regardless of whether or not fonts have layout tables present.

> Note: A variable font using OpenType Font Variations mechanisms is functionally equivalent to multiple non-variable fonts. Variable fonts do not need to be contained within a collection file. A collection file can include one or even multiple variable fonts, however, and may even combine variable and non-variable fonts.

The Noto font team might consider building one single `.ttc` font file that contains all variable Noto fonts packaged together. This could be useful for end-users who might fear that a large number of smaller font files is harder to deploy in their organizations. 

Note that fonts with `SVG ` outlines need “corresponding CFF or TT glyph descriptions“ (by which the spec means the presence of `glyf`, `CFF ` or `CFF2` tables in the font). Fonts with `sbix`, `EBDT` or `CBDT` bitmaps do not need any monochrome outline tables (`glyf`, `CFF ` or `CFF2`). 

There is one more distinguishing factor for the font flavors — the first 4 bytes of the font filer, i.e. the `sfntVersion` field. The spec is not sufficiently clear but it says: 

> OpenType fonts that contain TrueType outlines should use the value of `0x00010000` for the `sfntVersion`. OpenType fonts containing CFF data (version 1 or 2) should use the tag `OTTO` for `sfntVersion`.

Those values are used regardless if a font is a variable outline font or a static outline font. What’s not said is what to do if an OpenType font file does not include any outlines at all, only bitmap data (in `EBDT`, `CBDT` or `sbix` tables), but the practice is to treat such fonts as if they contained TrueType outlines, i.e. use the value 0x00010000.

**Comment by brawer** [comment]
Thanks for the long explanation. So, no change needed. (Regarding building Noto as one single file, there’s actually some work going on to have fewer deliverables than today, but that’s outside the topic of this bug).
