### ISSUE TITLE
Macedonian t, p and d italic versions are represented in a variant which is borrowed from Bulgarian fonts

### ISSUE THREAD

**Issue by schrepfler** [googlei18n/noto-fonts#888]
![image](https://cloud.githubusercontent.com/assets/3553/24677489/472a1338-1987-11e7-9514-e7574743f783.png)
I took a look at the Noto sample page for Noto Sans and Noto Serif and I noticed that the Macedonian italic version of letters t, p and d (т, п, д) are often represented in fonts according to the Bulgarian italic form. This is mostly historic, as there are almost no real Macedonian type foundries almost every Macedonian font has the Bulgarian representation of these letters in their italic form. 
I've attached an image showing the difference. I think there might be also a variant on other letters, perhaps the sh but I can't find more evidence on short notice.

https://www.google.com/get/noto/#sans-lgc (wondering if this is just because the site shows it's default Cyrillic version and there is somehow a way to enforce the Macedonian variant?)

**Comment by marekjez86** [comment]
@schrepfler : please look at https://github.com/googlei18n/noto-fonts/issues/794

This is the bug that I want to track. In my opinion, if you agree, this bug is a duplicate and would like to close it (feel free to add more info to https://github.com/googlei18n/noto-fonts/issues/794 ).

On a web page if one wants to Macedonian variant one can use lang="mk" like in the html below.
```i
<html lang="mk">
	<p style="font-weight:700">'б в г д ѓ п т з к ѐ ѝ'</p>
</html>
```

**Comment by schrepfler** [comment]
I think the other ticket is pretty good. There's also an accented e and i which is part of the official alphabet, I think this wiki page covers thinks well too https://en.m.wikipedia.org/wiki/Macedonian_alphabet and the cursive scan looks a bit better. Fine to close this item.
