### ISSUE TITLE
Noto Devanagari fonts

### ISSUE THREAD

**Issue by Appuraza** [googlei18n/noto-fonts#897]
Hi there,

This issue seems to be a common issue for all the Devanagari fonts and not only Noto fonts which has not been addressed yet. The Devanagari equivalent of a 'full-stop' or a 'period' is a Danda mark or '।'. However, unlike the language written in latin script where the 'full-stop' immediately follows the last alphabet of the sentence, there is always a small gap between the last alphabet of a sentence and the 'danda mark' in Devanagari script (e.g. तिमी आजै काठमाण्डौँ जाउ । म भोलि मात्रै आउँछु । ). The current practice to allow for this is to manually insert a space using the space-bar on the keyboard. However, this is potentially problematic when the text is formatted by a computer; sometimes the last word of the sentence remains on one line and the 'danda mark' goes to the next line looking something like this:

तिमी आजै काठमाण्डौँ जाउ 
। म भोलि मात्रै आउँछु ।

If the font design itself provided the Danda mark with a generous space on the left then this problem will be solved. This means that the a manual space between a word and a danda mark will not be necessary and during text formatting the danda mark will stick with the word before it whether the word remains in the same line or goes to the next line. For example, the formatting will be like:

Either:
तिमी आजै काठमाण्डौँ जाउ । 
म भोलि मात्रै आउँछु ।

Or:
तिमी आजै काठमाण्डौँ 
जाउ । म भोलि मात्रै आउँछु ।

Thanking you,

Apurba

**Comment by sommerluk** [comment]
In Frensh, the characters “?” and “!” have also a space before then. It’s either U+00A0 NO-BREAK SPACE or U+202F NARROW NO-BREAK SPACE (in my opinion nicer, but both are correct). Also MS Word adds this automatically when you type a “?” or “!” directly after an alphabetic character. Could this be useful for Devanagari ?

**Comment by Appuraza** [comment]
They are fine but the problem will be using so many keys just to create some space all the time can be tedious. It would be nicer if we have some space before ?, !, danda mark | and double danda mark || in built in the font itself for Devanagari especially for danda | mark as it is used as a full-stop and the usage is quite frequent. Also, I don't know if open office documents, and ms publisher have similar function that you mentioned.

**Comment by roozbehp** [comment]
appuraza@, the problem is the line breaking algorithm used by the software. Please check the Unicode line breaking algorithm and see if it handles the case of space+danada at the end of the words fine or not (http://unicode.org/reports/tr14/). If it doesn't, please contact the Unicode Consortium through http://www.unicode.org/reporting.html. If the Unicode algorithm is OK, you need to contact the makers of the software you are using that is showing the behavior and tell them they should follow Unicode. It's probably best to contact them anyway, even if the Unicode algorithm is incorrect, to tell them Unicode is wrong, you have contacted them, and the software needs to be fixed anyway.
