### ISSUE TITLE
Tai Viet issues

### ISSUE THREAD

**Issue by brawer** [googlei18n/noto-fonts#910]
In Noto Sans Tai Viet, is it intentional that the marks and base letter overlap in ꪤꪸ ? See the attached sample HTML [blt.html.zip](https://github.com/googlei18n/noto-fonts/files/980708/blt.html.zip). The page loads the Alpha version of Noto Sans directly from GitHub as a web font.

![image](https://cloud.githubusercontent.com/assets/1527880/25770173/7a18bc80-31e3-11e7-8b07-e6e1d97b1006.png)

Also, the type design for Noto Sans Tai Viet doesn’t seem to match the rest of Noto Sans. The shapes don’t seem very typographic; rather, it looks almost like a digitization of a hand-written font. Interestingly, this was also noticed by @lemzwerg when the two of us had worked together on auto-hinting the Tai Viet script.

Finally, the point size is inconsistent with the other scripts, although this might also be a bug in the fontmake pipeline (check by exporting the font from Glyphs.app, and see if it behaves differently).

**Comment by brawer** [comment]
Maybe @jvgaultney knows?

**Comment by moyogo** [comment]
@brawer Did you compare it with the previous release? That one has OT features and a different UPM.

**Comment by jvgaultney** [comment]
That font certainly does not look anything like Noto. In fact, it is a rather poor attempt to redraw the Tai Heritage font I personally designed starting in 1995. See http://scripts.sil.org/taiheritage. Terrible work from Monotype. You probably want someone to design a proper Noto-like version for you. Considering the poor work on this (and some other scripts), you probably want someone else than Monotype to do it. Ironically, my original is much more compatible with Noto Sans than this one!

**Comment by marekjez86** [comment]
![official-release](https://user-images.githubusercontent.com/13322623/27164429-21f7476e-5142-11e7-861f-ddf2720bb8b0.jpeg)

The official release, from   
src: url("https://rawgit.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSansTaiViet-Regular.ttf");
looks fine, so the problem is with my, unofficial conversion to glyphs. Monotype will provide the official conversion, but it will not change the glyphs. 

I will delete this font from noto-font-alpha.
