### ISSUE TITLE
map... to...

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#92]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.

.....

I korean... 

and map to sea of japan is not.... 

i wan't map name is donghae and korean (donghae) japan (sea of japan) plz...

Hu........... I not speak eng.. T_T;;;;;;;; 


```

Original issue reported on code.google.com by `tofind...@gmail.com` on 24 Jul 2014 at 12:48

**Comment by marekjez86** [comment]
jungshik this issue has nothing to do with fonts (noto or otherwise). Also comment "GoogleCodeExporter commented on Jun 8" appears to be a reasonable resolution/behavior. We either need to file an appropriate bug somewhere else and close this one or just add label working-as-expected and close this issue. Thank you.
