### ISSUE TITLE
Noto Sans Kannada rendering issue

### ISSUE THREAD

**Issue by ajjublr** [googlei18n/noto-fonts#938]
### Title 
  > Not rendering characters as expected

### Font 
  > NotoSansKannada-Regular.ttf and NotoSansKannada-Bold.ttf
  
### Where the font came from, and when
  >   Site: https://www.google.com/get/noto/#sans-knda

### Font Version
  > * Mac - [Font Version](https://imagebin.ca/v/3Qbc0q5htFzD)

![3qbc0q5htfzd](https://user-images.githubusercontent.com/13322623/27350494-5b4a0094-55af-11e7-908d-67e661dd430c.png)

### OS name and version
  > No, the font did not come pre-installed
  > Mac - OS Sierra - V. 10.12.05

### Application name and version
  > All Apps

### Issue
  > Character rendering order

### Screenshot
  > [Screenshot](https://imagebin.ca/v/3QbkENYt9DEj)

![3qbkenyt9dej](https://user-images.githubusercontent.com/13322623/27385533-e4f721bc-5647-11e7-8a28-aee38f09727e.png)

**Comment by ajjublr** [comment]
Thank you @marekjez86 ...

**Comment by marekjez86** [comment]
@ajjublr : could you type here the text that you used in the sample above? I'd like to be able to recreate it. thanks

**Comment by ajjublr** [comment]
Hi,

Just trying to give you the combination.
First letter in all of the following words..

ನೋಂದ, ರೋಂಗು, ಬೋಂಬೊ, ಗೋಂಡಾ

Reagrds

**Comment by marekjez86** [comment]
```html
<html lang="kn">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<style> @font-face { font-family: TestFont; src: url("https://rawgit.com/googlei18n/noto-fonts/master/unhinted/NotoSansKannada-Bold.ttf"); } body { font-family: TestFont; font-size: 10pt; } </style>
</head>
<p><span style="font-weight:700">ನೋಂದ, ರೋಂಗು, ಬೋಂಬೊ, ಗೋಂಡಾ</span></p>
<p><span style="font-weight:700">ೂೕಂ</span></p>
<p><span style="font-weight:700">ೕೂಂ</span></p>
</html>
```

on my MacOS Sierra with the above html I get the following rendering (looks different) than the top of the line you have, but I'm not certain if any of this is correct (please advise):

![kn-938](https://user-images.githubusercontent.com/13322623/27403908-1aa2532a-5681-11e7-81d7-e427a8771685.jpeg)

**Comment by ajjublr** [comment]
Yes,

I did check. No issue with browsers. Problem is with the apps in mac.

Thanks for the time. Will try to figure out the actual reason. 

Regards

**Comment by MayuraVerma** [comment]
this is already reported both at bugreport.apple.com and webkit.
https://bugs.webkit.org/show_bug.cgi?id=169499

Issue is with Apple Core Text Engine.

For open type font, either OS or application should run a text shaping engine.

At present there are four major text shaping engines. https://en.wikipedia.org/wiki/Complex_text_layout

Core Text for macOS (Mac OS, Apple applications such as safari, pages, keynotes,...)
Uniscribe and DirectWrite for Microsoft Windows (Windows OS and MS office)
HarfBuzz, a cross-platform library (used in Chrome browser in all platform including mac os, except iOS. Chrome on iOS uses coretext)
Adobe Worldready Composer (mainly for Adobe DTP applications)

Of all these shaping engines, core text and adobe worldready composer are most untested and buggy for Indic languages.

This is fixed in Mac OS High Sierra Public Beta 1 and iOS 11 beta

I have checked this mac OS high Sierra beta and iOS 11 beta, it is fixed.

This is not a font issue.

**Comment by MayuraVerma** [comment]
This is resolved in mac OS High Sierra and iOS 11.

**Comment by ajjublr** [comment]
Not yet..

**Comment by MayuraVerma** [comment]
Prajavani uses Noto Sans Kannada webfont.

http://m.prajavani.net/news/article/2016/04/22/403871.html
http://www.prajavani.net/news/article/2016/10/03/442512.html

![Screenshot](https://user-images.githubusercontent.com/14062593/32736332-ca604f22-c85c-11e7-96a5-c949dc7f18cc.jpg)

VijayaKarnataka uses Tunga webfont.
https://vijaykarnataka.indiatimes.com/topics/ಬಿಜೆಪಿಯ-ಡೋಂಗಿ-ಹಿಂದುತ್ವ-ಬಯಲು/

Please ensure you have updated to iOS version 11.1 or mac OS 10.13.1.

**Comment by ajjublr** [comment]
No issues with HTML documents, got problem with mac applications.

**Comment by ajjublr** [comment]
The first two are in SketchApp, issue is with most of the fonts except "Lohit Kannada". Last one is photoshop

![screen shot 2017-11-13 at 22 19 58](https://user-images.githubusercontent.com/1375338/32737759-ef818460-c8c0-11e7-95af-57aac3e63ab8.png)

**Comment by MayuraVerma** [comment]
@ajjublr this is a known Apple CoreText issue in iOS and mac OS, it is not related font. 

To verify: You can type the same text in notes app, which uses system default font "Kannada Sangam MN". 
You will notice the text will be broken as you have shown above. 
It is not related to any font but Apple CoreText shaping engine, which should be fixed soon (hopefully).

Can you please ping me at mayura(dot)verma(at)gmail

**Comment by ajjublr** [comment]
Thought so... Thanks.
